### ISSUE TITLE
more specific operations for MyChem `chembl.drug_mechanisms` data

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#100]
Related to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/532#issuecomment-1358768948

MyChem `chembl.drug_mechanisms` data, in subject-association-object format

* We want 1 association per unique combo of subject/object/action_type. 
    * Right now in MyChem, all data is aggregated by unique chemical (chem-centric format). So when a chemical has multiple drug_mechanisms, we can't retrieve only the sections that have a specific `action_type`. 
    * MyChem currently has [info for 5262 unique chemicals](https://mychem.info/v1/query?q=_exists_:%22chembl.drug_mechanisms%22)
* We want the gene ID to be NCBIGene (or UniProtKB or ENSEMBL ENSG maybe). 
    * Right now, it's CHEMBL.TARGET and Translator's Node Normalizer doesn't have cross-mappings/name-retrieval for that ID namespace

**Comment by colleenXu** [comment]
Related issue: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/316, JQ development work

**Comment by colleenXu** [comment]
One reason to create a pending api / adjust the parser for that resource: the gene ID being CHEMBL.TARGET is a problem that isn't solved by post-processing (JQ).

**Comment by newgene** [comment]
Cross-ref a related issue here: https://github.com/biothings/mygene.info/issues/105 (mapping from CHEMBL Target ID to gene id)

**Comment by colleenXu** [comment]
## Notes on the data

### Drugs 

Not all drugs are "Small molecule". In rough order most to least:
* almost 75% are "Small molecule" (4727/6306)
* almost 14% are "Antibody" (866/6306)
* other:
    * Protein
    * Unknown
    * Enzyme
    * Oligonucleotide
    * Oligosaccharide
    * Gene
    * Cell

### Targets

Not all targets are human stuff. In rough order from most to least:
* almost 83% are "Homo sapiens" (5229/6306)
* others are bacteria, virus, fungi, or `- N/A -` targets

Mot all targets are proteins. In rough order from most to least:
* almost 69% are "SINGLE PROTEIN" (4155/6306)
* almost 11% are "PROTEIN FAMILY" (667/6306)
* Other:
    * `- N/A -`
    * PROTEIN COMPLEX
    * PROTEIN COMPLEX GROUP
    * NUCLEIC-ACID
    * SMALL MOLECULE
    * PROTEIN NUCLEIC-ACID COMPLEX
    * OLIGOSACCHARIDE
    * MACROMOLECULE
    * METAL
    * SUBCELLULAR
    * CHIMERIC PROTEIN
    * LIPID
    * SELECTIVITY GROUP
    * PROTEIN-PROTEIN INTERACTION
    * UNKNOWN
    * ORGANISM
    * CELL-LINE

### categories of drug mechanisms

when browsing chembl https://www.ebi.ac.uk/chembl/g/#browse/mechanisms_of_action (roughly in order of most to least):
* INHIBITOR
* ANTAGONIST
* AGONIST
* `- N/A -`  🧇
* BINDING AGENT  🧇
* BLOCKER
* MODULATOR  🧇
* POSITIVE ALLOSTERIC MODULATOR
* HYDROLYTIC ENYZME
* ACTIVATOR
* Other (in alphabetic order, not most to least)
    * ALLOSTERIC ANTAGONIST
    * ANTISENSE INHIBITOR
    * CHELATING AGENT 
    * CROSS-LINKING AGENT 🧇
    * DEGRADER
    * DISRUPTING AGENT
    * INVERSE AGONIST
    * NEGATIVE ALLOSTERIC MODULATOR
    * NEGATIVE MODULATOR
    * OPENER
    * OTHER 🧇
    * OXIDATIVE ENYZME
    * PARTIAL AGONIST
    * POSITIVE MODULATOR
    * PROTEOLYTIC ENZYME
    * REDUCING AGENT 
    * RELEASING AGENT
    * RNAI INHIBITOR
    * SEQUESTERING AGENT
    * STABILISER
    * SUBSTRATE
    * VACCINE ANTIGEN 

🧇  not as helpful for the creative-mode issue [532](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/532#issuecomment-1358768948)

**Comment by colleenXu** [comment]
## Example of current MyChem structure vs association-based structure 

### Background

[ANG1005 (CHEMBL1089636)](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1089636/) has two drug-mechanisms that are different categories:
* `BINDING AGENT` for `Prolow-density lipoprotein receptor-related protein 1` (chembl target CHEMBL4630884 aka [Q07954](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL4630884/))
* `INHIBITOR` for `tubulin` (chembl target [CHEMBL2095182](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL2095182/) aka a bunch of UniProt accessions because it's a protein complex group)

### In MyChem

these two drug-mechanisms are nested inside the chembl.drug_mechanisms field of the MyChem record for this chemical: https://mychem.info/v1/query?q=_exists_:%22chembl.drug_mechanisms%22%20AND%20chembl.molecule_chembl_id:CHEMBL1089636. This means BTE post-processing ([JQ](https://github.com/biothings/api-respone-transform.js/pull/38#issuecomment-1365556891)?) is needed to retrieve only the `INHIBITOR` drug-mechanism (or vice versa).  

```
{
    "chembl": {
        "molecule_chembl_id": "CHEMBL1089636",
        "drug_mechanisms": [
            {"action_type": "INHIBITOR", "references": {...}, "binding_site_name": null, "target_chembl_id": "CHEMBL2095182", "target_uniprot_accession": ["P68371", ...]},
            {"action_type": "BINDING_AGENT", "references": {...}, "binding_site_name": null, "target_chembl_id": "CHEMBL4630884", "target_uniprot_accession": "Q07954"}
        ]
    }
}
```
### association-based structure

However, if we use an association-based structure, we can make two separate records. And these two records can be retrieved separately depending on what association.action_type is set to when querying.  

```
{
    "subject": { "drug_chembl_id": "CHEMBL1089636", ...},
    "association": { "action_type": "INHIBITOR", "references": {...}, "binding_site_name": null},
    "object": { "target_chembl_id": "CHEMBL2095182", "target_uniprot_accession": ["P68371", ...]}
},
{
    "subject": { "drug_chembl_id": "CHEMBL1089636", ...},
    "association": { "action_type": "BINDING_AGENT", "references": {...}, "binding_site_name": null},
    "object": { "target_chembl_id": "CHEMBL4630884", "target_uniprot_accession": "Q07954"}
}
```

**Comment by rjawesome** [comment]
I've started a pending API python script if the association-based structure is preferred. Will post repo soon.

**Comment by colleenXu** [comment]
Note, I'm not sure how to handle the records that may lack an "action_type" value...they seem to lack a lot of information...

https://mychem.info/v1/query?q=_exists_:%22chembl.drug_mechanisms.action_type%22
![Screen Shot 2022-12-28 at 8 38 58 PM](https://user-images.githubusercontent.com/43731687/209904189-b64347d5-2263-4eb1-96c0-12a6c59d1c56.png)

**Comment by rjawesome** [comment]
See https://github.com/rjawesome/mychem-drug-mechanisms

**Comment by colleenXu** [comment]
At the moment, creating a new API is not necessary. 

* target IDs (ensembl gene or uniprotkb) were added https://github.com/biothings/mychem.info/issues/151
* Wrote more general operations for now to cover this dataset 
    * for biolink 3.1.1 (currently on dev/CI instances): https://github.com/NCATS-Tangerine/translator-api-registry/commit/db32e8917b577e12397378cdaef05008ee2f95be
    * for biolink 2.4.8 (currently on test/prod instances): https://github.com/NCATS-Tangerine/translator-api-registry/commit/83775ed97e6bb4c8a1d52ed7a1cb773ccc4e3d53 
* Haven't done this yet: using MyChem's new list_filter function (discussed here https://github.com/biothings/api-respone-transform.js/pull/38#issuecomment-1381087737), I could write operations in the chem -> gene direction that are more specific (however not all records would be covered). See 

I therefore moved this issue to "on-hold"

**Comment by colleenXu** [comment]
Leaving open; in the future, we may want to write more specific operations (see the third bullet point "haven't done this yet" in the post above)

**Comment by colleenXu** [comment]
Leaving open; in the future, we may want to write more specific operations (see the third bullet point "haven't done this yet" in the post above). I therefore moved this issue to "on-hold"

**Comment by colleenXu** [comment]
Closing for now: will open another issue to consider writing more specific operations using filter/jmespath
