### ISSUE TITLE
New API based on MyChem `drugcentral.bioactivity` data

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#101]
Related to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/532#issuecomment-1358768948

MyChem `drugcentral.bioactivity` data, in subject-association-object format

* We want 1 association per unique combo of subject/object/action_type. 
    * Right now in MyChem, all data is aggregated by unique chemical (chem-centric format). So when a chemical has multiple bioactivity, we can't retrieve only the sections that have a specific `action_type`. 
    * MyChem currently has [info for 2772 unique chemicals](https://mychem.info/v1/query?q=_exists_:%22drugcentral.bioactivity%22)
* We want the gene ID to be UniProtKB (or NCBIGene or ENSEMBL ENSG maybe). 
    * Right now, it's UniProtKB but [119 chemicals lack the UniProtKB record...and their bioactivity info looks odd (not acting on genes?)](https://mychem.info/v1/query?q=_exists_:%22drugcentral.bioactivity%22%20AND%20(NOT%20_exists_:%22drugcentral.bioactivity.uniprot.uniprot_id%22))

**Comment by colleenXu** [comment]
Related issue: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/316, JQ development work

**Comment by rjawesome** [comment]
With jq implemented, exisiting API can be used with modifications to smartapi yaml. See [this comment](https://github.com/biothings/api-respone-transform.js/pull/38#issuecomment-1365556891)

**Comment by colleenXu** [comment]
Noting: Some chemicals have many `drugcentral.bioactivity` elements, and only some of those elements have the `action_type` field that is most useful for filtering for specific relationships. (Note: `act_type` has the same issue as #99, where IC50 and Ki might be mean "inhibitory relationship" but that may depend on the actual associated value being large / small...)

Example: [methotrexate's drugcentral info in MyChem](https://mychem.info/v1/chem/FBOZXECLQNJBKD-ZDUSSCGKSA-N?fields=drugcentral)

**Comment by colleenXu** [comment]
More notes on "action_type" and targets: 
* many bioactivity entries seem to be missing "action_types"; this seems to be a bigger issue than for chembl.drug_mechanism (for example, [aripiprazole](https://drugcentral.org/drugcard/242#Bio has 45 bioactivity entries but only 6 have action_type values
* many bioactivity entries use non-human targets (for example, out of aripiprazole's 6 bioactivites with action_type values, only 3 are human). The association method / BTE post-processing with JQ may be helpful here, if we want to filter for only human targets (vs non-human orthologs)...

**Comment by colleenXu** [comment]
### Example of current MyChem structure vs association-based structure 

(basically repeating https://github.com/biothings/pending.api/issues/100#issuecomment-1366968402 using an example from this resource)

<details>
<summary>expand here for the example</summary>

### Background

[aripiprazole (CHEMBL1112)](https://drugcentral.org/drugcard/242#Bio) has multiple bioactivity entries with different categories (action_types). I'll give two of them as examples:
* `PARTIAL AGONIST` for `D(2) dopamine receptor` ([P14416](https://www.uniprot.org/uniprotkb/P14416/entry))
* `ANTAGONIST` for `5-hydroxytryptamine receptor 2A` ([P28223](https://www.uniprot.org/uniprotkb/P28223/entry))

### In MyChem

these two bioactivity entries are nested inside the drugcentral.bioactivity field of the MyChem record for this chemical: https://mychem.info/v1/chem/60795?fields=drugcentral. This means BTE post-processing ([JQ](https://github.com/biothings/api-respone-transform.js/pull/38#issuecomment-1365556891)?) is needed to retrieve only the `ANTAGONIST` bioactivity (or vice versa).  

```
{
    "drugcentral": {
        "bioactivity": "CHEMBL1089636",
        "drug_mechanisms": [
            {"action_type": "PARTIAL_AGONIST", "act_source": "WOMBAT-PK",..., "uniprot": [ {"uniprot_id": "P14416", "gene_symbol": "DRD2", ...} ] },
            {"action_type": "ANTAGONIST", "act_source": "WOMBAT-PK",..., "uniprot": [ {"uniprot_id": "P28223", "gene_symbol": "HTR2A", ...} ] }
        ]
    }
}
```
### association-based structure

However, if we use an association-based structure, we can make two separate records. And these two records can be retrieved separately depending on what association.action_type is set to when querying.  

```
{
    "subject": { "drug_chembl_id": "CHEMBL1112", ...},
    "association": { "action_type": "PARTIAL_AGONIST", "act_source": "WOMBAT-PK",...},
    "object": { "uniprot_id": "P14416", "uniprot_gene_symbol": "DRD2", ...}
},
{
    "subject": { "drug_chembl_id": "CHEMBL1112", ...},
    "association": { "action_type": "ANTAGONIST", "act_source": "WOMBAT-PK",...},
    "object": { "uniprot_id": "P28223", "uniprot_gene_symbol": "HTR2A", ...}
}
``` 

</details>

**Comment by colleenXu** [comment]
At the moment, creating a new API is not necessary. Using MyChem's new list_filter function (discussed here https://github.com/biothings/api-respone-transform.js/pull/38#issuecomment-1381087737), I can write operations in the chem -> gene direction that are more specific (however not all records are covered). 

Andrew decided that this was fine to try out.

The edits to the SmartAPI yamls are
for biolink 3.1.1 (currently on dev/CI instances): https://github.com/NCATS-Tangerine/translator-api-registry/commit/5d4391abd6947f5ed27ba95e4879f0ee622b3f91
for biolink 2.4.8 (currently on test/prod instances): https://github.com/NCATS-Tangerine/translator-api-registry/commit/81e6e486f99fb63fa1de2e469ce79884c3cf0f99

**Comment by colleenXu** [comment]
Closing. If we notice an issue with this (not able to retrieve some desired info in the chem -> gene direction, want to be able to use more specific predicates in the gene -> chem direction), we'll reopen.

**Comment by colleenXu** [comment]
@newgene 

two issues encountered when trying to write operations:
* I'd like to be able to "list_filter" for items that are MISSING the `drugcentral.bioactivity.action_type` field. At the moment, I have to specify 1 or more string values. 
* Getting this issue addressed would help with writing operations: https://github.com/biothings/mychem.info/issues/153
