### ISSUE TITLE
API Multiomics_ClinicalTrials update

### ISSUE THREAD

**Issue by GitHubbit** [biothings/pending.api#106]
- API URL: https://biothings.ncats.io/multiomics_clinicaltrials_kp
- Github URL: https://github.com/GitHubbit/Multiomics_ClinicalTrials_KP FORKED TO https://github.com/Hadlock-Lab/Multiomics_ClinicalTrials_KP
- Git Branch/Commit: main [634d75c](https://github.com/Hadlock-Lab/Multiomics_ClinicalTrials_KP/commit/634d75cc79bb291067d2ec204bec0f01e3340238)
- No. Documents: 55,313
- Structure of Documents: Only trivial changes made. Parser attribute ids have been changed from "original_knowledge_source" to "primary_knowledge_source" and "aggregate_knowledge_source" where relevant. No other changes were made

**Comment by erikyao** [comment]
Hi @colleenXu @GitHubbit, it's updated, see https://biothings.ncats.io/multiomics_clinicaltrials_kp

**Comment by GitHubbit** [comment]
Thank you Yao!
-Kamileh
