### ISSUE TITLE
API update for Multiomics-BigGIM-DrugResponse

### ISSUE THREAD

**Issue by gloriachin** [biothings/pending.api#107]
Need to update Multiomics-BigGIM-DrugResponse API to add the primary_knowledge_source.
Parser has been updated in the github repo: https://github.com/gloriachin/BigGIM_Parser
The revision includes adding the biolink attribute: primary_knowledge_source.
If the association is from other resources, we add the upstream knowledge source as the primary knowledge source. 
If the association is computed from data, we assign "infores:biothings-multiomics-biggim-drugresponse" as the primary knowledge source. We also have a [github page](https://github.com/NCATSTranslator/Translator-All/wiki/Big-GIM-II:-Drug-Response-KP) that can link to explain how the graph is extracted.

**Comment by erikyao** [comment]
Hi @gloriachin, it's updated. See https://biothings.ncats.io/biggim_drugresponse_kp

**Comment by gloriachin** [comment]
Thank you!
<img width="798" alt="image" src="https://user-images.githubusercontent.com/2994757/225732482-75bb0475-b4bb-4abb-b105-9741eee1ba5d.png">

The version number in the parser has been changed.

**Comment by colleenXu** [comment]
@gloriachin FYI, Translator expects only 1 primary knowledge source per Edge. The current reasoner-validator will raise an error: https://github.com/NCATSTranslator/reasoner-validator/blob/master/reasoner_validator/codes.yaml#L173
