### ISSUE TITLE
API Multiomics-BigGIM-DrugResponse KP updates

### ISSUE THREAD

**Issue by gloriachin** [biothings/pending.api#111]
API URL: https://biothings.ncats.io/biggim_drugresponse_kp
Parser GitHub URL: https://github.com/gloriachin/BigGIM_Parser
Git branch/commit: Master

Structure of documents: 
Fix the primary knowledge source;
Added sources property; 
change id-prefix from PUBMED.COMPOUND to pubmed.compound

**Comment by gloriachin** [comment]
@erikyao Could you help to update the [biggim_drugresponse_kp](https://biothings.ncats.io/biggim_drugresponse_kp) so it will fit with the TRAPI 1.4 (adding sources). Let me know if more revision is needed. Thank you very much.

**Comment by gloriachin** [comment]
Hi @colleenXu The field name are named as "pubchem_compound". But we could change it to pubchem_cid if needed.

**Comment by colleenXu** [comment]
This isn't my area of expertise so I'll leave it to you and Yao. I'll just note...

* the mapping in this [file](https://github.com/gloriachin/BigGIM_Parser/blob/main/mapping.py) has multiple spellings for a pubchem compound field, and I think this file is supposed to match the data in the API (does it?)
* I notice multiple spellings of pubchem compound in the [parser](https://github.com/gloriachin/BigGIM_Parser/blob/main/BigGIM_Parser.py#L80), and I don't notice anywhere where those spellings changed to a consistent format.

**Comment by gloriachin** [comment]
@colleenXu Thank you very much for the quick response, it has been used for the get_xref() function.

**Comment by colleenXu** [comment]
BTE's code has advanced so BTE and x-bte annotation in the SmartAPI yaml can handle ID-prefix spellings. As long as an ID-namespace is spelled consistently in the field names / data, I think it's fine...

**Comment by erikyao** [comment]
@gloriachin @colleenXu it's updated!
