### ISSUE TITLE
API Multiomics Clinical Trials Update

### ISSUE THREAD

**Issue by GitHubbit** [biothings/pending.api#114]
- API URL: https://biothings.ncats.io/multiomics_clinicaltrials_kp
- Github URL: https://github.com/Hadlock-Lab/Multiomics_ClinicalTrials_KP
- Git Branch/Commit: Master 7da4704
- No. Documents: 55,313 (only change is to parser, to comply with TRAPI 1.4 update (https://github.com/uhbrar/ReasonerAPI/blob/update_guide/MigrationAndImplementationGuide1-4.md))
- Structure of Documents: single record
`{
  "_id": "01028716_C0686586_C0059985",
  "subject": {
    "UMLS": "C0686586",
    "name": "acute leukemia in remission",
    "type": "Disease"
  },
  "association": {
    "predicate": "related_to",
    "edge_attributes": [
      {
        "attribute_type_id": "clinicaltrials_id",
        "value": "NCT01028716"
      },
      {
        "attribute_type_id": "biolink:aggregator_knowledge_source",
        "value": "infores:biothings-multiomics-clinicaltrials"
      },
      {
        "attribute_type_id": "biolink:primary_knowledge_source",
        "value": "infores:aact"
      },
      {
        "attribute_type_id": "biolink:supporting_data_source",
        "value": "infores:clinicaltrials"
      }
    ]
  },
  "object": {
    "UMLS": "C0059985",
    "name": "fludarabine",
    "type": "Treatment"
  },
  "source": {
    "edge_sources": [
      {
        "resource_id": "infores:biothings-multiomics-clinicaltrials",
        "resource_role": "aggregator_knowledge_source"
      },
      {
        "resource_id": "infores:aact",
        "resource_role": "primary_knowledge_source"
      },
      {
        "resource_id": "infores:clinicaltrials",
        "resource_role": "supporting_data_source"
      }
    ]
  }`

**Comment by erikyao** [comment]
@GitHubbit @colleenXu API updated. Please let me know if I can be of any other help.

**Comment by GitHubbit** [comment]
We had a small update
We had feedback that users preferred the subject and object to be reversed, as in "Intervention--treats--Disease" as opposed to "Disease--treated by--Intervention". In addition, feedback from Data Modeling suggested reassigning the primary and aggregator knowledge sources, and removing supporting data source. We have made updates in the parser accordingly. 
Please let me know if KG can be re-deployed. Thank you!

**Comment by colleenXu** [comment]
@GitHubbit Just a heads-up: It sounds like those changes would require updates to the SmartAPI yamls (x-bte annotation) after these changes are deployed. 

---

And something that came to mind when reading your message. I'm happy to have a convo over it, but I also don't think it's a big deal / you have to make changes ASAP to anything...

I'm not sure whether the feedback can be addressed by adjusting the parser/data. Off the top of my head, that seems to be more related to...
* "what is the direction of the QEdges"
* whether KG Edges must be in the "canonical directions" of predicates in the biolink-model (related to https://github.com/biothings/biothings_explorer/issues/476), even if that then doesn't match with the direction of the QEdge it's bound to
* whether the API record-structure + x-bte annotation allows full data retrieval when retrieving the statement/record using the subject or the object ("forward" or "reverse") - and they do in this case, which is a good thing

**Comment by erikyao** [comment]
@GitHubbit @colleenXu API updated

**Comment by colleenXu** [comment]
It looks like this issue has been addressed:
* API was updated May 2023
* x-bte annotation was updated June 2023
