### ISSUE TITLE
Data source: DrugMAP

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#115]
from [NAR Database issue 2023](https://academic.oup.com/nar/issue/51/D1):

paper: https://academic.oup.com/nar/article/51/D1/D1288/6761740
data: http://drugmap.idrblab.net/full-data-download

**Comment by colleenXu** [comment]
duplicate of https://github.com/biothings/pending.api/issues/112 ?

**Comment by newgene** [comment]
yep, close this one...
