### ISSUE TITLE
Multiomics-BigGIM-DrugResponse API updates

### ISSUE THREAD

**Issue by gloriachin** [biothings/pending.api#119]
[Yaml file](https://github.com/gloriachin/BigGIM_Parser/tree/main/BET_YAML) has been revised according to the guidance from Colleen. The update includes adding sources in the parameters and x-bte-response-mapping section. 
@colleenXu Could you help to check it whether the updates fit with the current BET system?

**Comment by gloriachin** [comment]
API endpoint: https://biothings.transltr.io/biggim_drugresponse_kp
YAML file: https://github.com/gloriachin/BigGIM_Parser/tree/main/BET_YAML
Paser directory: https://github.com/gloriachin/BigGIM_Parser/

An example of one record: https://biothings.transltr.io/biggim_drugresponse_kp/association/Gene_biolink:associated_with_resistance_to_SmallMolecule_Input_DrugResponse_expr_auc_gdsc_08312022.csv_149182

**Comment by colleenXu** [comment]
@gloriachin 

First: I think issues in this github repo have traditionally been for BioThings API deployments, and not for SmartAPI yaml editing. It think it's up to @erikyao and @newgene whether they want to have issues like this here....but I advise making these issues in the repo the [registered yaml](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/drug_response_kp/smartapi.yaml) is in. 

Second: do you have permission to make a branch/fork of the translator-api-registry repo? If you modify the registered yaml there, it's easier to compare / track / merge changes (and merging to update the registered yaml will happen once all instances are on TRAPI 1.4). So I suggest doing this and making a PR in that repo...

**Comment by gloriachin** [comment]
@colleenXu 
I revised the [yaml](https://github.com/gloriachin/translator-api-registry/tree/master/drug_response_kp) file in a fork of translator-api-registry repo.

**Comment by colleenXu** [comment]
@gloriachin

It's good that a forked file has been made to contain the TRAPI-1.4-support-specific changes. We can connect BTE's instances that are on TRAPI-1.4 to that forked file, even though it's not fully fixed yet. 

One issue: the field you added, `association.sources` appears to not exist in the API. You should be adding the JSON-notation-path of the field that contains the TRAPI 1.4 sources data.

**Comment by gloriachin** [comment]
Here is an example of the record:
[⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
            "_id": "Gene_biolink:associated_with_resistance_to_SmallMolecule_Input_DrugResponse_expr_auc_gdsc_08312022.csv_5509",
            "_score": 2.4046109,
            "attributes": [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#)[
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "attribute_type_id": "EDAM:data_0951",
                    "attributes": [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#)[
                       [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                            "attribute_type_id": "NCIT:C53236",
                            "description": "Spearman Correlation Test was used to extract the association",
                            "value": "NCIT:C53249",
                            "value_type_id": "biolink:id"
                        }
                    ],
                    "value": 0.0008900739749078,
                    "value_type_id": "EDAM:data_1669"
                },
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "attribute_type_id": "biolink:supporting_study_size",
                    "value": 14
                },
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "attribute_type_id": "biolink:dataset",
                    "value": "GDSC"
                },
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "attribute_type_id": "biolink:publications",
                    "value": "PMID:27397505"
                },
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "attribute_type_id": "biolink:subject_aspect_qualifier",
                    "value": "Gene expression"
                },
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "attribute_type_id": "biolink:object_aspect_qualifier",
                    "value": "AUC"
                },
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "attribute_source": "infores:biothings-multiomics-biggim-drugresponse",
                    "attribute_type_id": "biolink:context_qualifier",
                    "value": "MONDO:0004056"
                }
            ],
            "object": [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                "id": "pubchem.compound:5284616",
                "name": "AZD7762",
                "pubchem_compound": "pubchem.compound:5284616",
                "type": "SmallMolecule",
                "xref": "https://pubchem.ncbi.nlm.nih.gov/compound/5284616"
            },
            "predicate": "biolink:associated_with_resistance_to",
            "sources": [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#)[
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "resource_id": "infores:biothings-multiomics-biggim-drugresponse",
                    "resource_role": "primary_knowledge_source"
                },
               [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                    "resource_id": "infores:gdsc",
                    "resource_role": "biolink:supporting_data_source"
                }
            ],
            "subject": [⊖](https://biothings.transltr.io/biggim_drugresponse_kp#){
                "NCBIGene": "NCBIGene:729522",
                "id": "NCBIGene:729522",
                "name": "AACSP1",
                "type": "Gene",
                "xref": "https://www.ncbi.nlm.nih.gov/gene/729522"
            }
        },

**Comment by colleenXu** [comment]
Looks like this issue has been addressed:
It was about x-bte annotation, and a series of [x-bte annotation updates](https://github.com/NCATS-Tangerine/translator-api-registry/commits/master/drug_response_kp) were made May + June 2023. [The update to TRAPI 1.4 with sources was done in August 2023](https://github.com/NCATS-Tangerine/translator-api-registry/commit/084dfab35bdc5d77357e73a8fc6ef3867d104c36#diff-23bb19aedcf83b44862801e58726340c98c7f62146e3655b76bab6ea8d3d5ef3)
