### ISSUE TITLE
new API for CTD

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#12]
Heterogeneous association network from [CTD](https://toxnet.nlm.nih.gov/newtoxnet/ctd.htm)

May need to split into multiple APIs based on the entity-types.

**Comment by andrewsu** [comment]
I believe this is obsolete given the automat CTD APIs https://smart-api.info/registry?q=ctd.  @newgene do you agree?

**Comment by newgene** [comment]
Sure, we can close this one.
