### ISSUE TITLE
web ui: avoid to use url string in the example queries

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#129]
One example here: https://biothings.ci.transltr.io/rare_source

<img width="1047" alt="image" src="https://github.com/biothings/pending.api/assets/130158/4a615ccd-32ce-4cd0-afb4-d89d34ca2e58">

url string is typically not a good for example queries, we should skip them when generating example queries.

**Comment by marcodarko** [comment]
Will be addressed in https://github.com/biothings/pending.api/pull/134

**Comment by newgene** [comment]
fixed in the merged https://github.com/biothings/pending.api/pull/134
