### ISSUE TITLE
post mortem of DNS issue with biothings.transltr.io / biothings.nacts.io

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#133]
Recently, we had an issue where the APIs on biothings.ncats.io were non-responsive with the following error:

```
{
"Message": "User: anonymous is not authorized to perform: es:ESHttpGet because no resource-based policy allows the es:ESHttpGet action"
}
```

a restart of nginx on biothings.ncats.io resolved the issue. @newgene [diagnosed](https://ncatstranslator.slack.com/archives/C030684LH7U/p1690285222166599?thread_ts=1690234044.328309&cid=C030684LH7U) the cause as follows:

> the root of this issue, from what I can tell, is related to the change of public IP associated with [biothings.transltr.io](http://biothings.transltr.io/). [biothings.nacts.io](http://biothings.nacts.io/) host uses nginx to proxy to [biothings.transltr.io](http://biothings.transltr.io/). Looks like Nginx resolves its IP only at the starting time, then cache the value, so when the IP changes, it cannot reach the real server. Restart nginx fixes it. Do you have any suggestions for a good solution in this case? Either make a fixed IP for [biothings.transltr.io](http://biothings.transltr.io/) or somehow make nginx to resolve DNS automatically when something is wrong.

Given key people are currently traveling, and given that biothings.ncats.io is a core piece of infrastructure for BTE and Translator, I'm creating this issue so we can revisit whether we need to make any changes as a result.

**Comment by newgene** [comment]
We confirmed with the ITRB team that the IP address resolved from the biothings.transltr.io hostname will always be dynamic (from the use of AWS application load balancer). In this case, we will apply a nginx configuration change to force nginx to resolve the hostname. The solution is pretty much documented [here](https://serverfault.com/questions/240476/how-to-force-nginx-to-resolve-dns-of-a-dynamic-hostname-everytime-when-doing-p/593003#593003).

**Comment by newgene** [comment]
changes on nginx were just applied.

**Comment by newgene** [comment]
Close this issue for now, but we can re-open it if we see the issue again.
