### ISSUE TITLE
creating additional semmeddb api endpoints with custom query filters

### ISSUE THREAD

**Issue by cmaceves** [biothings/pending.api#139]
Hi! So in order to investigate the affect of [NER stats](https://github.com/biothings/biothings_explorer/issues/670) on the performance of return query accuracy, we'd like to create several filtering options for the predication.object_score and predication.subject_score fields to query. The filtering logic for each of the 5 endpoints should be 
```semmeddb/query?q=... &predication.subject_score:>N&predication.object_score>N```
where N=[800,900,950,975,990] in each of the five endpoints respectively.  Jmespath filter won't work in this case, because you can only modify a single field at a time with the current setup.

**Comment by newgene** [comment]
@cmaceves you should still be able to use `jmespath` filter for this purpose, using `prediction` as the target field, and include both `subject_score` and `object_score` criteria in the filter.

**Comment by newgene** [comment]
👍 thanks for the clarification, yes, agree that this logic in jmespath can be a bit complex, better to implement separated in Python.

**Comment by newgene** [comment]
With this fix+improvment on the biothings sdk, we can use `jmespath` parameter to get what we want for this issue. Here is [an example](https://pending.biothings.io/semmeddb/query?jmespath=.|{predication:%20predication[?subject_score%20%3E%20`900`],%20subject:subject,%20object:object,%20predicate:predicate}|{predication_count:%20predication|length(@),%20pmid_count:%20predication[].pmid|unique_count(@),subject:subject,%20object:object,%20predicate:predicate}) with this particular `jmespath` value:

```
jmespath=.|{predication: predication[?subject_score > `900`], subject:subject, object:object, predicate:predicate}|{predication_count: predication|length(@), pmid_count: predication[].pmid|unique_count(@), subject:subject, object:object, predicate:predicate}
```
