### ISSUE TITLE
Create 3 APIs for PFOCR "flavors"

### ISSUE THREAD

**Issue by AlexanderPico** [biothings/pending.api#148]
If it's not too much trouble, it would be helpful to have 3 APIs for the PFOCR content. This way we could test the 3 "flavors" in actual use cases to help decide which one(s) to maintain long term.

The three ndjson files have the exactly same structure and fields, and be parsed by the same [parser.py](https://github.com/biothings/pfocr/blob/master/parser.py) script, swapping in filenames.  The [version](https://github.com/biothings/pfocr/blob/master/version.py) for this release (for all 3 files) is 2023-04-01.

Here are the input files and their unique nicknames:

1. all: https://www.dropbox.com/scl/fi/yw4ijp0gkm17muju3awgs/bte_chemicals_diseases_genes_all.ndjson?rlkey=ntqdd32uybdi3b514dvc36tmn&dl=0
2. synonyms: https://www.dropbox.com/scl/fi/xlyjpqj9dw79jp1y1lwbr/bte_chemicals_diseases_genes_synonyms.ndjson?rlkey=o2x0lhrab10svdou1lrl6jv4j&dl=0
3. strict: https://www.dropbox.com/scl/fi/igoqupv3qi138vm9scfxs/bte_chemicals_diseases_genes_strict.ndjson?rlkey=50icp9qn4jqjr5l8ubiaknulz&dl=0

Here are some stat on their size differences:
1. all: 71,423 figures, 69 genes per figure(ave), 65.6MiB
2. synonyms: 71,423 figures, 33 genes per figure(ave), 55.1MiB
3. strict: 65,320 figures, 21 genes per figure(ave), 46.5MiB

**Comment by AlexanderPico** [comment]
Feedback so far: let's use "strict"

**Comment by newgene** [comment]
Ideally, if we can add a flagging field to indicate three flavors, I think we can create one API with a query parameter to switch between flavors.

**Comment by ctrl-schaff** [comment]
Hey @AlexanderPico is there anyway way we can get a public dropbox link for three files? We're having to perform more work than expected to download the files and thought it might be easier to change the original source we're pulling from. @everaldorodrigo

**Comment by AlexanderPico** [comment]
Sorry! I thought those were public links... If I go the site and "copy link" I get the same URLs I shared already.

They are too big for email of GH repos.... What do you recommend?

**Comment by AlexanderPico** [comment]
Eh, the 50MB limit is "soft" limit on GitHub, so here you go :)
https://github.com/AlexanderPico/pfocr-files

**Comment by colleenXu** [comment]
Current examples:

- https://biothings.transltr.io/pfocr/query?q=associatedWith.pmc:PMC3255783&all
- https://biothings.transltr.io/pfocr/query?q=associatedWith.pmc:PMC3255783&synonyms
- https://biothings.transltr.io/pfocr/query?q=associatedWith.pmc:PMC3255783&strict
