### ISSUE TITLE
Create a new API for clinicaltrials.gov data

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#149]
clinicaltrials.gov does provide their own API, but it seems their batch query is not very easy to use. Creating our own API of clinicaltrials.gov trial data could benefit multiple projects.

* This is their own API:
   https://clinicaltrials.gov/data-about-studies/learn-about-api

   Can use `/studies` endpoint to iterate through all study objects.

* They do provide csv file download, but csv file contains less data than their API output.

* About their data structure: 
   https://clinicaltrials.gov/data-about-studies/study-data-structure

**Comment by ZubairQazi** [comment]
Code repository: https://github.com/biothings/clinicaltrials_gov/tree/apidumper
