### ISSUE TITLE
Implement OpenTelemetry integration for Pending APIs

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#150]
Translator consortium plan to use [Open Telemetry](https://opentelemetry.io/) to track Translator-related applications.

This tornado integration module might be useful:

https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/tornado/tornado.html

And Translator should provide a centralized server to harvest the tracking data.

**Comment by newgene** [comment]
The demo code from Translator: https://github.com/TranslatorSRI/Jaeger-demo

**Comment by newgene** [comment]
We can start to try on one of our API (e.g. semmeddb) and the Annotator API (see annotator.py for its handler)

**Comment by everaldorodrigo** [comment]
The OpenTelemetry integration was implemented here https://github.com/biothings/pending.api/pull/151 and refactored here https://github.com/biothings/pending.api/pull/168.
