### ISSUE TITLE
BioThings FoodData Central parser change

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#170]
I suggest changing the FOODON IDs to be numeric (remove the FOODON_  part of the ID). 

Biolink-model folks have told us to use the BioRegistry regex strings for ID-format, and [BioRegistry shows that FOODON IDs should be 8-digit numeric](https://bioregistry.io/registry/foodon). Right now our IDs all start with "FOODON_". We hadn't heard this policy clarification when [we were setting up this API and wondering about the ID format](https://github.com/biothings/pending.api/issues/66#issuecomment-1205665860). 

---

And something to think on and decide: in ~22% of the dataset, the nutrient wasn't actually found in the food ([object.nutrientAmount = 0](https://biothings.ncats.io/fooddata/query?q=object.nutrientAmount:0)). I'm not sure if we want to keep this info or not. 

It's not an issue for BTE use because I can use the BioThings filter parameter to only retrieve records with amount > 0. 

(based on https://github.com/biothings/biothings_explorer/issues/683#issuecomment-1870035991)

**Comment by colleenXu** [comment]
@everaldorodrigo @newgene 

It looks like this issue is being addressed, yay! 

If you have decided on keeping/removing the [object.nutrientAmount = 0](https://biothings.ncats.io/fooddata/query?q=object.nutrientAmount:0) records, can you add that to this issue?

**Comment by colleenXu** [comment]
Did we want to keep this issue open until it was deployed on all instances (ncats.io and all ITRB instances transltr.io)?

**Comment by newgene** [comment]
yes, labelled it as "on CI" for now.

**Comment by ctrl-schaff** [comment]
Verified by @colleenXu. Food on id is more numeric
