### ISSUE TITLE
Columbia Open Health Data

### ISSUE THREAD

**Issue by kevinxin90** [biothings/pending.api#19]
source: https://u.pcloud.link/publink/show?code=XZ3ibtkZlJt9yHczhp5NjlGkui6E4uvTXL7y

The link contains a zip file, we only need to parse the "paired_concept_counts_associations" file.

type: EHR records

Manual dumper

First generate a static JSON/pickle file to store xrefs for all omop IDs (primary id used in omop)
Use this endpoint: http://cohd.smart-api.info/#/OMOP/xrefFromOMOP
may also consider this one: http://cohd.smart-api.info/#/OMOP/mapToStandardConceptID

Need to create two APIs based on this "paired_concept_counts_associations" file.

- First API

    - Retrieves observed clinical frequencies of all pairs of concepts given a concept id.
    - sort the result, and keep only the first 100
    - Similar to this endpoint: http://cohd.smart-api.info/#/Clinical%20Frequencies/associatedConceptFreq
    - need to add xrefs field for both the primary concept(_id) as well as all associated concepts (outputs)
    ```
    {
      "_id": "...",
      "xrefs": {
          "umls": ...,
          "mesh": ...,
      },
      "results": [
        {
          "associated_concept_id": 2213216,
          "associated_concept_name": "Cytopathology, selective cellular enhancement technique with interpretation (eg, liquid based slide preparation method), except cervical or vaginal",
          "associated_domain_id": "Measurement",
          "concept_count": 330,
          "concept_frequency": 0.0001843131625848748,
          "concept_id": 192855,
          "dataset_id": 1
        },
        {
          "associated_concept_id": 4214956,
          "associated_concept_name": "History of clinical finding in subject",
          "associated_domain_id": "Observation",
          "concept_count": 329,
          "concept_frequency": 0.00018375463784976913,
          "concept_id": 192855,
          "dataset_id": 1
        }
       ]
    }
     

    ```

- Second API

    - Retrieves observed clinical frequencies of a pair of concepts.
    - Similar to this endpoint: http://cohd.smart-api.info/#/Clinical%20Frequencies/pairedConceptFreq
    - need to add xrefs for both concept1 and concept2
    - use form concept1-concept2 to represent _id

    ```
    {
      "_id": "concept1-concept2",
      "concept1": {
         "omop": "....",
         "xrefs": {
             "mesh": ...,
             "umls": ....
         }
      },
      "concept2": {
         "omop": "....",
         "xrefs": {
             "mesh": ...,
             "umls": ....
         }
      },
      "results": [
        {
          "concept_count": 10,
          "concept_frequency": 0.000005585247351056813,
          "concept_id_1": 192855,
          "concept_id_2": 2008271
        }
      ]
    }
    ```

**Comment by andrewsu** [comment]
After checking with @CaseyTa, closing this ticket...
