### ISSUE TITLE
Multiomics Clinical Trials parser update for KL/AT

### ISSUE THREAD

**Issue by GitHubbit** [biothings/pending.api#190]
- API URL: https://biothings.ncats.io/multiomics_clinicaltrials_kp
- Github URL: https://github.com/Hadlock-Lab/Multiomics_ClinicalTrials_KP
- Git branch/commit: [b0b7e27](https://github.com/GitHubbit/Multiomics_ClinicalTrials_KP/commit/b0b7e2772468305e2b489beccbc3cd400b5d1d2e)
- No. Documents: [55,313 documents](https://biothings.ncats.io/multiomics_clinicaltrials_kp)
- Main change: Added knowledge_level and agent_type to each edge. No other changes.

**Comment by everaldorodrigo** [comment]
The last changes were released to the CI environment. Let me know if the data looks good to you.

**Comment by gglusman** [comment]
This can be closed. There is a new version of this KP.

**Comment by gglusman** [comment]
No, the relevant issue is #200.

**Comment by ctrl-schaff** [comment]
> No, the relevant issue is #200.
Oh sorry I copied the wrong one. Yeah that's the one I intended to reference. Perfect thanks!
