### ISSUE TITLE
multiomics drug_approvals initial deployment, v0.1

### ISSUE THREAD

**Issue by gglusman** [biothings/pending.api#196]
API URL: https://biothings.ncats.io/multiomics_drug_approvals_kp
Github URL: https://github.com/multiomicsKP/drug_approvals_kp
Git branch/commit: https://github.com/multiomicsKP/drug_approvals_kp/commit/c98fbbc0bf5bc943c371f04f31741643fdffdaed
No. Documents: 76,533
Main change: Initial deployment.

**Comment by ctrl-schaff** [comment]
[CI environment deployment](https://biothings.ci.transltr.io/multiomics_drug_approvals_kp)

**Comment by gglusman** [comment]
I modified the parser in a number of ways, no changes to the underlying content, but the output will be a bit different now in terms of edge_sources metadata.
Git commit: https://github.com/multiomicsKP/drug_approvals_kp/commit/91b7cbe95ea77e0863a8651f460df119b03c9787
Could you please refresh the parser? Thanks!
