### ISSUE TITLE
multiomics clinical_trials v2.1

### ISSUE THREAD

**Issue by gglusman** [biothings/pending.api#200]
See next comment for updated request.

~~API URL: https://biothings.ncats.io/multiomics_clinicaltrials_kp
Github URL: https://github.com/multiomicsKP/clinical_trials_kp
Git branch/commit: https://github.com/multiomicsKP/clinical_trials_kp/commit/821da5998e65726b9ca1b25ad7732c96ab885449
No. Documents: 63,018
Main change: Initial deployment of version 2.0, to replace existing version 1.03.~~

**Comment by gglusman** [comment]
New version... please use the following:

API URL: https://biothings.ncats.io/multiomics_clinicaltrials_kp
Github URL: https://github.com/multiomicsKP/clinical_trials_kp
Git branch/commit: https://github.com/multiomicsKP/clinical_trials_kp/commit/d41a25c6a1f5db13c215f44495d406a56267c893
No. Documents: 63,083
Main change: updated data; modified row identifier structure; modified representation of some trial attributes; modified parser accordingly.

**Comment by gglusman** [comment]
I just replaced the edges source file in the google bucket to correct the representation of knowledge_level. Everything else remains the same.

**Comment by ctrl-schaff** [comment]
@gglusman While attempting to release this we ran into a mapping issue.

```
"association": {
        "label": {
            "__type__:str": {}
        },
        "attributes": {
            "__type__:list": {
                "attribute_type_id": {
                    "__type__:str": {}
                },
                "value": {
                    "__type__:str": {},
                    "__type__:bool": {}
                }
            }
        },
```

the `value` field has potential string and boolean values. 

```
...
            # knowledge level
            edge_attributes.append(
                {
                    "attribute_type_id": "biolink:knowledge_level",
                    "value": line['knowledge_level'],
                }
            )

            # agent type
            edge_attributes.append(
                {
                    "attribute_type_id": "biolink:agent_type",
                     "value": line['agent_type'],
                }
            )
            
            # max research phase
            edge_attributes.append(
                {
                    "attribute_type_id": "biolink:max_research_phase",
                     "value": str(max_phase),
                }
            )
            
            # elevate to prediction
            edge_attributes.append(
                {
                    "attribute_type_id": "elevate_to_prediction",
                     "value": elevate_to_prediction,
                }
            )
...
```

I believe `elevate_to_predication` is always a boolean, whereas the other three values are always a string

**Comment by gglusman** [comment]
Indeed, some values are expected to be strings and some booleans. Should I cast all as strings?
Generically, would that always be the case? How should numerical values be represented?

**Comment by ctrl-schaff** [comment]
@gglusman So in this case it's because for one field you have it set for both string and boolean. For the `edge_attributes` list, the `attribute_type_id` and the `value` in this case are the fields. The mapping that I refer to above is an elasticsearch mapping which supports [typical data types](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html). I believe elasticsearch recently added support for one-to-many field data types, but I don't believe our backend supports that at the moment. So in this case we can either cast the boolean to string so that the `value` field matches the other types. This would require changing the type of `elevate_to_predication`. Or `elevate_to_prediction` can somehow get modified to a different field related to the `edge_attributes`. This would require changing the structure of your parser. Generically we (and by we I really mean elasticsearch since it's handling this) are usually able to infer the type whether it be string or numerically integer or float. Looking at the full mapping below, everything else generated as expected with most of the fields populated as some from of string keyword. For this specific case the `study_size` field appears to be exclusively integer based.
```
{
    "_id": {
        "__type__:str": {}
    },
    "subject": {
        "id": {
            "__type__:str": {}
        },
        "unii": {
            "__type__:str": {}
        },
        "name": {
            "__type__:splitstr": {}
        },
        "type": {
            "__type__:str": {}
        },
        "chebi": {
            "__type__:str": {}
        },
        "pubchem_compound": {
            "__type__:str": {}
        },
        "chembl_compound": {
            "__type__:str": {}
        }
    },
    "association": {
        "label": {
            "__type__:str": {}
        },
        "attributes": {
            "__type__:list": {
                "attribute_type_id": {
                    "__type__:str": {}
                },
                "value": {
                    "__type__:str": {},
                    "__type__:bool": {}
                }
            }
        },
        "sources": {
            "__type__:list": {
                "resource_id": {
                    "__type__:str": {}
                },
                "resource_role": {
                    "__type__:str": {}
                },
                "source_record_urls": {
                    "__type__:list": {
                        "__type__:str": {}
                    }
                }
            }
        },
        "supporting_studies": {
            "__type__:list": {
                "id": {
                    "__type__:str": {}
                },
                "tested_intervention": {
                    "__type__:str": {}
                },
                "phase": {
                    "__type__:str": {}
                },
                "study_size": {
                    "__type__:int": {}
                },
                "status": {
                    "__type__:splitstr": {}
                }
            }
        }
    },
    "object": {
        "id": {
            "__type__:str": {}
        },
        "mondo": {
            "__type__:str": {}
        },
        "name": {
            "__type__:splitstr": {}
        },
        "type": {
            "__type__:str": {}
        },
        "hp": {
            "__type__:str": {}
        }
    }
}
```

**Comment by gglusman** [comment]
Fixed -> https://github.com/multiomicsKP/clinical_trials_kp/commit/e43ce0b72b3a8f5693ab8f3ba71c6fdd9bcae741

**Comment by ctrl-schaff** [comment]
@gglusman Alright sorry but one other issue we discussed while creating a build relates to handling of the `study_size` field. The field `study_size` can be set to "NA" in cases where we cannot convert to a integer. We'll have to a have a different value in the case of an exception or modify the value of N so that they're all strings. 

```python
try:
    N = int(N)
except:
    N = "NA"
```

In this case we have an empty string within the `enroll`. 

```python
(Pdb) enroll
['53', '217', '12', '10', '35', '212', '96', '100', '', '245', '27', '23', '32', '89', '1252', '424', '24', '54', '22', '84', '16', '51', '1805', '100', '23', '20', '6586', '50', '45', '114', '315', '52', '224', '1145', '75', '72', '375', '154', '80', '24', '174', '43', '103', '60', '260', '18', '25', '25', '11', '43', '889', '35', '37', '165', '124']
```

And in this case `enroll` is `NaN`
```python
(Pdb) N
'nan'
(Pdb) enroll
['nan']
(Pdb) line
id                 648e2f5e-6945-3e07-9094-56d6ac1e5f96
subject                                     CHEBI:18332
predicate               biolink:mentioned_in_trials_for
object                                       HP:0008223
subject_name                                L-thyroxine
object_name                  subclinical hypothyroidism
category                            biolink:Association
knowledge_level                     knowledge_assertion
agent_type                                 manual_agent
nctid                                       NCT00535561
phase                                                 1
overall_status                                Completed
start_date                                       2007-6
enrollment                                          NaN
enrollment_type                                     NaN
unii                                    UNII:Q51BO43MG4
Name: 3317, dtype: object
(Pdb) line.isnan()
*** AttributeError: 'Series' object has no attribute 'isnan'. Did you mean: 'isna'?
(Pdb) line.isna()
id                 False
subject            False
predicate          False
object             False
subject_name       False
object_name        False
category           False
knowledge_level    False
agent_type         False
nctid              False
phase              False
overall_status     False
start_date         False
enrollment          True
enrollment_type     True
unii               False
Name: 3317, dtype: bool
```

**Comment by gglusman** [comment]
@ctrl-schaff Can we keep the study_size field as an string? It's a comma-delimited list of numbers.

**Comment by ctrl-schaff** [comment]
> @ctrl-schaff Can we keep the study_size field as an string? It's a comma-delimited list of numbers, which could have just one value, or more.

@gglusman Yeah that's perfectly fine

**Comment by gglusman** [comment]
Updated file_parser.py to resolve this: https://github.com/multiomicsKP/clinical_trials_kp/commit/b7147e3a51c142ab3f8464a7dc13bbddec29ca1e

**Comment by ctrl-schaff** [comment]
[CI Release](https://biothings.ci.transltr.io/multiomics_clinicaltrials_kp) @gglusman
