### ISSUE TITLE
multiomics drug_approvals update, v0.2

### ISSUE THREAD

**Issue by gglusman** [biothings/pending.api#202]
API URL: https://biothings.ncats.io/multiomics_drug_approvals_kp
Github URL: https://github.com/multiomicsKP/drug_approvals_kp
Git branch/commit: https://github.com/multiomicsKP/drug_approvals_kp/commit/d0d562ff1ea3c2040aafe678809c5110e2db4491
No. Documents: 76,533
Main change: Modified row identifier structure, updated parser.

**Comment by gglusman** [comment]
I just replaced the edges source file in the google bucket to correct the representation of knowledge_level. Everything else remains the same.

**Comment by ctrl-schaff** [comment]
@gglusman @everaldorodrigo I don't know what changed between the prior release and this release, but we no longer have access to the data files stored on the google storage anymore.

`Error while downloading 'https://storage.googleapis.com/multiomics_provider_kp_data/drug_approvals/drug_approvals_kg_nodes_v0.2.tsv' (status: 403, reason: Forbidden)`

**Comment by gglusman** [comment]
I just made them world-readable - again. I had done that yesterday, not sure why it didn't stay like that.
Thanks!

**Comment by everaldorodrigo** [comment]
Hey @gglusman, could you add a `,` in the end of this line? We don't have permission to make changes in this repository.
- https://github.com/multiomicsKP/clinical_trials_kp/blob/0fbc4225d4e4298e40eb7e1597b291f58b592e79/manifest.json#L14

**Comment by gglusman** [comment]
Oops, done!

**Comment by everaldorodrigo** [comment]
Thank you so much :)

**Comment by ctrl-schaff** [comment]
[CI environment release](https://biothings.ci.transltr.io/multiomics_drug_approvals_kpl) @gglusman

**Comment by gglusman** [comment]
Awesome, thanks!

**Comment by ctrl-schaff** [comment]
Released to all instances. Closing for now
