### ISSUE TITLE
BioThings PFOCR issues

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#203]
Two things I've noticed:

(1) queries like https://biothings.transltr.io/pfocr/query?q=associatedWith.mentions.genes.ncbigene:5879 return no hits even when there are records with that value ([example](https://biothings.transltr.io/pfocr/geneset/PMC4243705__nihms642954f4)). Maybe it's because there's a misspelling in the [metadata/fields](https://biothings.transltr.io/pfocr/metadata/fields) entry - which says associatedWith.mentions.genes.**bcbigene**...

(2) For the PFOCR flavors, I'm not sure how to specify them in the OpenAPI spec / x-bte annotation. They're not regular query-level parameters like fields/size/jmespath/etc....can they be? ([see previous Slack convo](https://suwulab.slack.com/archives/CC19LHAF2/p1709154454648489?thread_ts=1709151492.317709&cid=CC19LHAF2)) @newgene 

Refs:
* https://github.com/biothings/pending.api/issues/148
* https://github.com/biothings/biothings_explorer/issues/778

**Comment by colleenXu** [comment]
@newgene @everaldorodrigo I think the first point is easy to fix - and a bug that needs addressing...

I think the second point may need some more discussion

**Comment by everaldorodrigo** [comment]
@colleenXu the first point fix was released to the CI, Test, and Production environments.

**Comment by everaldorodrigo** [comment]
@colleenXu, according to `Openapi` specs we could modify the endpoint to accept a new parameter called `flavor`. Ex:
- flavor=all
- flavor=strict
- flavor=synonymous

We also could keep both behaviors. The current one and the new one using a parameter called flavor.

What are your thoughts?

**Comment by newgene** [comment]
I would just use `flavor=all|strict|synonymous`, don't think we need to keep both.

**Comment by colleenXu** [comment]
I think a new parameter like flavor sounds perfect!

**Comment by everaldorodrigo** [comment]
@newgene @colleenXu the `flavor=all|strict|synonymous` was deployed to the CI environment. The default value for `flavor` parameter is `all`

Examples for testing:
- https://biothings.ci.transltr.io/pfocr/query?q=associatedWith.mentions.genes.ncbigene:5879&flavor=strict
- https://biothings.ci.transltr.io/pfocr/query?q=associatedWith.mentions.genes.ncbigene:5879&flavor=synonyms
- https://biothings.ci.transltr.io/pfocr/query?q=associatedWith.mentions.genes.ncbigene:5879&flavor=all
- https://biothings.ci.transltr.io/pfocr/query?q=associatedWith.mentions.genes.ncbigene:5879

**Comment by colleenXu** [comment]
I have two observations for you/Alex Pico to check on. Otherwise, I think this looks fine and ready to deploy to all instances! 

Two observations:
* It looks like only the gene list differs for the 3 flavors (not chemicals or diseases). Is this correct @AlexanderPico? 
* The document order was different for the different flavors. I don't think this is important for Translator use, but I want to point it out in case you think it's a problem. 

To check behavior, I took a few individual document/records and compared the mention counts. For example, I checked `PMC6883319__gr8`...
* [setting flavor to `all`](https://biothings.ci.transltr.io/pfocr/query?q=_id:PMC6883319__gr8&flavor=all) looks the same as [not setting flavor](https://biothings.ci.transltr.io/pfocr/query?q=_id:PMC6883319__gr8): 8 chemicals, 1 disease, 152 genes
* vs [setting flavor to `synonyms`](https://biothings.ci.transltr.io/pfocr/query?q=_id:PMC6883319__gr8&flavor=synonyms): 69 genes (other entity counts didn't change)
* vs [setting flavor to `strict`](https://biothings.ci.transltr.io/pfocr/query?q=_id:PMC6883319__gr8&flavor=strict): 32 genes (other entity counts didn't change)

**Comment by colleenXu** [comment]
And a note to myself: Andrew said I don't need to add this parameter's information to SmartAPI annotation right now. We're using the default (all) right now.

**Comment by AlexanderPico** [comment]
> It looks like only the gene list differs for the 3 flavors (not chemicals or diseases). Is this correct @AlexanderPico?

Correct

**Comment by colleenXu** [comment]
@everaldorodrigo @ctrl-schaff @newgene 

Your thoughts on [my second observation](https://github.com/biothings/pending.api/issues/203#issuecomment-2174815252)?

**Comment by newgene** [comment]
order does not matter across different `flavor` parameter values, as they are different set of hits.

**Comment by colleenXu** [comment]
So from my perspective, this seems good and ready to deploy to all instances.

**Comment by colleenXu** [comment]
Let's use the tags to track deployment? Based on the Slack convos, it looks like this is on Test now...

**Comment by colleenXu** [comment]
@everaldorodrigo Are the PFOCR flavors already deployed to Prod? Does that mean this issue can be closed?

**Comment by everaldorodrigo** [comment]
Hi @colleenXu, yes they were deployed to Prod.
