### ISSUE TITLE
DGIdb API

### ISSUE THREAD

**Issue by kevinxin90** [biothings/pending.api#21]
Source file: http://dgidb.org/data/interactions.tsv

Represent each line of the tsv file as a JSON document, hash all values in the line and use it as the **_id** for the document.

Output (use the first row as an example):
```json
{
  "_id": "b59670809cf23553",
  "subject": {
    "NCBIGene": "1022",
    "SYMBOL": "CDK7",
    "id": "NCBIGene:1022"
  },
  "object": {
    "name": "BMS-387032",
    "CHEMBL.COMPOUND": "CHEMBL296468",
    "id": "CHEMBL.COMPOUND:CHEMBL29468"
  },
  "association": {
    "edge_label": "decreases_activity_of",
    "relation_name": "inhibitor",
    "pubmed": [],
    "provided_by": "CancerCommons"
  }
}
```

Specifications:

1. Gene
  - For subject.id field, use entrez_id (NCBIGene) value by default
  - If entrez_id field is empty, use mygene.info service to query for the NCBIGene ID based on gene_name field, e.g. http://mygene.info/v3/query?q=symbol:CDK7&fields=entrezgene&species=human
  - If couldn't resolve using mygene, use SYMBOL:{gene_name} as subject.id

2. Chemical
  - For object.id field, use drug_chembl_id(CHEMBL.COMPOUND) value by default
  - If drug_chembl_id is empty, use mychem.info service to query for CHEMBL.COMPOUND ID based on drug_name, e.g. http://mychem.info/v1/query?q=chembl.pref_name:riluzole&fields=chembl.molecule_chembl_id
  - If couldn't resolve using mychem, use name:{drug_name} as object.id

3. edge_label

  - consult this [yaml file](https://github.com/RTXteam/RTX/blob/master/code/kg2/predicate-remap.yaml) to convert the value of interaction_types into biolink predicate, e.g. "DGIdb:inhibitor" should be converted to "decreases_activity_of"
  - keep the value of "interaction_types" as  the value for association.relation_name field

4. pubmed
  - could be multiple, split by "," into a list

5. provided_by
  - use the value of interaction_claim_source

**Comment by ravila4** [comment]
Repo: https://github.com/ravila4/DGIdb

**Comment by kevinxin90** [comment]
Live API: https://biothings.ncats.io/dgidb
