### ISSUE TITLE
update pfocr API metadata

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#219]
I think https://biothings.transltr.io/pfocr/metadata needs to be updated so the `code` points to https://github.com/biothings/pending.api/tree/master/plugins/pfocr. (or perhaps some specific commit?)

**Comment by ctrl-schaff** [comment]
@andrewsu I think when you click on that link it points specifically to the commit hash `"commit": "4e0870b". When you click the url it appears to open to that commit as well. Would you like a different behavior?

**Comment by andrewsu** [comment]
That looks like the perfect behavior, thanks!
