### ISSUE TITLE
link APIs listed at http://pending.biothings.io/ with corresponding code repo 

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#23]
If I am interested in creating an issue for a specific pending API (e.g., http://pending.biothings.io/hpo) it's not clear where I should create that issue.  It's also not clear where the parser code lives in case I want to do a pull request.  As one possible low-tech solution, we could have a simple table or list in the README that links to the relevant parser repo.

**Comment by newgene** [comment]
"Code" link?
![image](https://user-images.githubusercontent.com/130158/120371559-d9e86300-c2ca-11eb-8c1f-be3d4bbc0d67.png)

**Comment by andrewsu** [comment]
Ahh yes, that is perfect, missed that.  Thanks!
