### ISSUE TITLE
add gene-phenotype associations to HPO API

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#24]
The Human Phenotype Ontology project curates annotations between genes and phenotypes.  Full files are downloadable here: https://hpo.jax.org/app/download/annotation.  Would be very useful to add these annotations to the pending HPO API.  After that, would be good to add these info to the SmartAPI record (https://smart-api.info/registry?q=a5b0ec6bfde5008984d4b6cde402d61f), and specifically the mapping file (https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/hpo/smartapi.yaml).

**Comment by newgene** [comment]
@yichuanma95

The existing data plugin here: https://github.com/kevinxin90/hpo

The current live API here: https://pending.biothings.io/HPO

**Comment by yichuanma95** [comment]
When I click on the link for downloading annotations, nothing is happening.

**Comment by andrewsu** [comment]
I see some weird browser-based security issue.  But you should be able to copy/paste (or wget) these URLs directly: http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.txt and http://purl.obolibrary.org/obo/hp/hpoa/phenotype_to_genes.txt

**Comment by yichuanma95** [comment]
I forked the original data plugin for the HPO API and modified it so that each phenotype has a list of annotations. Here's an example:
```
{
"_id": "HP:0032330",
"_version": 1,
"ancestors": [
"HP:0000001",
"HP:0000118",
"HP:0000818",
"HP:0012029"
],
"annotations": [
{
"disease_id": "ORPHA:90793",
"gd_source": "orphadata",
"gene": {
"id": "1586",
"symbol": "CYP17A1"
}
},
{
"disease_id": "ORPHA:90795",
"gd_source": "orphadata",
"gene": {
"id": "1584",
"symbol": "CYP11B1"
}
}
],
"children": [],
"comment": "Increased urinary 11-deoxycorticosterone is associated with congenital adrenal hyperplasia due to 11 beta-hydroxylase (CYP11B1) deficiency.",
"def": "\"An abnormally elevated concentration or amount of 11-deoxycorticosterone in the urine.\" [OHSU:jpgourdine, PMID:10689646]",
"descendants": [],
"hp": "HP:0032330",
"name": "Increased urinary 11-deoxycorticosterone level",
"parents": [
"HP:0012029"
],
"property_value": [
"[http://purl.org/dc/elements/1.1/date 2019-02-18T13:52:04Z xsd:dateTime](http://purl.org/dc/elements/1.1/date%202019-02-18T13:52:04Z%20xsd:dateTime)"
],
"synonym": {}
}
```

**Comment by yichuanma95** [comment]
My repo is here: https://github.com/yichuanma95/hpo

**Comment by newgene** [comment]
assign to @ericz1803 for the deployment

**Comment by ericz1803** [comment]
Deployed.

**Comment by andrewsu** [comment]
confirmed that gene-phenotype annotations are available through the API https://biothings.ncats.io/hpo/phenotype/HP:0032330

```
{
  "_id": "HP:0032330",
  "_version": 1,
  "ancestors": [
    "HP:0000818",
    "HP:0012029",
    "HP:0000118",
    "HP:0000001"
  ],
  "annotations": [
    {
      "disease_id": "ORPHA:90793",
      "gene": {
        "id": "1586",
        "symbol": "CYP17A1"
      }
    },
    {
      "disease_id": "ORPHA:90795",
      "gene": {
        "id": "1584",
        "symbol": "CYP11B1"
      }
    }
  ],
  "children": [],
  "comment": "Increased urinary 11-deoxycorticosterone is associated with congenital adrenal hyperplasia due to 11 beta-hydroxylase (CYP11B1) deficiency.",
  "def": "An abnormally elevated concentration or amount of 11-deoxycorticosterone in the urine. [https://orcid.org/0000-0001-9969-8610, PMID:10689646]",
  "descendants": [],
  "hp": "HP:0032330",
  "name": "Increased urinary 11-deoxycorticosterone level",
  "parents": [
    "HP:0012029"
  ],
  "property_value": [
    "http://purl.org/dc/elements/1.1/date \"2019-02-18T13:52:04Z\" xsd:dateTime",
    "http://purl.org/dc/terms/creator https://orcid.org/0000-0002-0736-9199"
  ],
  "synonym": {}
}
```
