### ISSUE TITLE
API pfocr update

### ISSUE THREAD

**Issue by AlexanderPico** [biothings/pending.api#241]
- API URL: https://biothings.transltr.io/pfocr
- Github URL: https://github.com/AlexanderPico/pfocr-files
- Git Branch/Commit: main [ef94c74](https://github.com/AlexanderPico/pfocr-files/commit/ef94c749486820ad65f587fe6e9edd0563f4bf62)
- No. Documents: 3 files
- Structure of Documents: No change

**Comment by AlexanderPico** [comment]
Updated files at GitHub URL (above) to include chebi and doid identifiers in addition to mesh for chemicals and diseases.

**Comment by colleenXu** [comment]
@ctrl-schaff @AlexanderPico 

This is the issue tracking the PFOCR update that includes chebi/doid fields, right? 
I imagine it's best to track its deployment...so I added project/tags...

**Comment by AlexanderPico** [comment]
@colleenXu , thanks. Yes, this is for update fields, and also for 5000 new pathway figures published in recent months.

**Comment by colleenXu** [comment]
Do you think this issue can be closed, if the PFOCR update is live on all pending BioThings instances already? 

Or maybe tagged with "In Prod" so we know it's in Prod already?
