### ISSUE TITLE
UI: API page does not pick up the correct total count

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#252]
In this new API page:

https://biothings.ci.transltr.io/annotator_extra

The total count appears as the first source's count, instead of the total count from the `stats.total` field.

This API is different from most of other APIs. It includes multiple sources in one API (most of others are typically a single-source API).

<img width="817" alt="image" src="https://github.com/user-attachments/assets/9af2038f-ea68-47bf-b955-233c4a41d75c">

**Comment by marcodarko** [comment]
@newgene so is this like a special case or should ALL APIs do the same? I wanna ask before I make any changes just to make sure :)

**Comment by newgene** [comment]
You can confirm, I believe all API metadata should have the top-level `stats.total`.

**Comment by newgene** [comment]
but other metadata fields, like version, description, source etc., can be a special case for this API. Because it has three sources, instead of just one. We might a discussion to decide the best way to display them.

**Comment by marcodarko** [comment]
requested VPN access to tunnel the CI instance, so waiting on a response to get this working

**Comment by marcodarko** [comment]
Issue will be addressed in PR https://github.com/biothings/pending.api/pull/255

**Comment by ctrl-schaff** [comment]
@marcodarko can I close this issue?

**Comment by marcodarko** [comment]
@ctrl-schaff yes please, thank you!

**Comment by ctrl-schaff** [comment]
Thank @marcodarko! Closing as completed
