### ISSUE TITLE
creating new API for TISSUES dataset

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#26]
### Adding TISSUES for BTE

From the same lab that made [DISEASES](https://diseases.jensenlab.org/About) (which is [one of our pending biothings apis](http://pending.biothings.io/DISEASES))....

There's [TISSUES](https://tissues.jensenlab.org/About), a similar resource but it has manually curated, experimental, and text-mined associations between **genes and tissues** in several species (including human).

It looks like it may update weekly. Its downloads are available [here](https://tissues.jensenlab.org/Downloads). 

Note: I think this lab does have an API available, but it might not have the batch query / other abilities of biothings apis.

---

### refactoring DISEASES

There may need to be discussion for both the DISEASES and TISSUES apis on whether to keep the "channels" (assertions from different kinds of knowledge like manually curated knowledge vs experimental vs text-mined) in separate fields (tissues.knowledge vs tissues.text-mined)....

Right now, DISEASES is putting all the "channels" info together under one field for access. So BTE doesn't have a simple way to assign different Biolink predicates to the assertions made with different kinds of knowledge...

**Comment by newgene** [comment]
Data plugin repo: https://github.com/kevinxin90/DISEASES

**Comment by colleenXu** [comment]
What is the status of this issue? 

I suggest using an association-based data structure for both APIs, if possible. This would allow us to access the association properties whether we query with a subject (disease) or an object (gene). 

It would also help to further parse the evidence information.

The example below is a record from [here](https://pending.biothings.io/diseases/query?q=DISEASES.doid:"DOID:0060041"):

<details>
<summary>current</summary>
```
{
"DISEASES": {
                "_license": "https://creativecommons.org/licenses/by/3.0/",
                "associatedWith": [
                   {
                        "category": "experiments",
                        "confidence": 0.835,
                        "ensembl": "ENSP00000482335",
                        "evidence": "p-value = 7e-06",
                        "source": "DistiLD",
                        "symbol": "MAP7"
                    }
                ],
                "doid": "DOID:0060041",
                "name": "Autism spectrum disorder"
            },
```
</details>

<details>
<summary>desired?</summary>
```
{
    "subject": {
        "DOID": "DOID:0060041",
         "name": "Autism spectrum disorder"
    },
    "association": {
        "category": "experiments",
        "confidence": 0.835,
        "evidence": {
            "p-value" : 7e-06
        },
        "source": "DistiLD"
    },
    "object": {
        "symbol": "MAP7",
         "ensembl_protein": "ENSP00000482335"
    }
}
```

**Comment by NikkiBytes** [comment]
@colleenXu after some discussion, I am going to create a separate ticket for refactoring DISEASES. 

TISSUES parser is up to par with the current DISEASES structure and the data plugin is being pushed to pending.api. 

Code from DISEASES was reused to set TISSUES up, but I did add some upgrades that I can add to DISEASES when we move forward with a refactored structure.  

Example record: 

```
 {
        "_id": "BTO:0000000",
        "TISSUES": {
            "associatedWith": [
                {
                    "ensembl": "18S_rRNA",
                    "symbol": "18S_rRNA",
                    "zscore": 6.111,
                    "confidence": 3.055,
                    "category": "textmining"
                }
            ],
            "tissue_id": "BTO:0000000",
            "tissue_name": "tissues, cell types and enzyme sources"
        }
    }

**Comment by colleenXu** [comment]
@NikkiBytes @newgene @andrewsu I'm willing to work with whatever is ready. 

However:
* The example triple uses a very general subject ID (the root term of the ontology??)...so I'm wondering if we could remove data with that ID from the API...
* I think there are benefits to the association-based modeling that involves refactoring of both APIs (as mentioned above)

**Comment by NikkiBytes** [comment]
> However:
> 
> * The example triple uses a very general subject ID (the root term of the ontology??)...so I'm wondering if we could remove data with that ID from the API...

You're referring to the `BT0:` id correct? So, I pulled these as the three unique ids headers found in the `tissue_id` fields: `{'BTO', 'CLDB', 'CLBD'} ` . The DISEASES parser filtered the ids and extracted the `DOID` ids. We can definitely do something similar here.

**Comment by colleenXu** [comment]
@NikkiBytes this is specifically for BTO:0000000...it seems like a very general term that isn't useful

**Comment by NikkiBytes** [comment]
After some discussion we have mapped out 3 possibilities for the structure @colleenXu , based on the desired structure you mentioned. 

We consider if we want a separate object for the associations, considering the event that the same association will appear in 2 files. 
#
We can .... 
1.  Keep each record/association separate ( a record for each row, for each file).
2. Combine records based on associations, and have 1 record per association per file ( a record for each association in each file)
3. Combine records based on association across files, and have 1 record per association for all files ( a record for each association across all files)



Here are the 3 files for reference: 

Text mining file: 
<img width="984" alt="Screen Shot 2021-12-17 at 6 31 09 PM" src="https://user-images.githubusercontent.com/19334243/146619782-2ae33f77-99ab-4b03-8715-9451e02c286c.png">

Experiments file:  
<img width="1001" alt="Screen Shot 2021-12-17 at 6 46 24 PM" src="https://user-images.githubusercontent.com/19334243/146620132-5b8cabde-cd75-48c3-93be-a03748f100e1.png">

Knowledge file: 
<img width="992" alt="Screen Shot 2021-12-17 at 6 47 38 PM" src="https://user-images.githubusercontent.com/19334243/146620179-779d03d6-ac65-4bec-b045-050e05411dce.png">

**Comment by colleenXu** [comment]
@NikkiBytes sorry for the late response. 

It sound like having 3 separate fields (diseases.text-mined, diseases.knowledge, diseases.experiments) - one per file - would work? Also, I notice that the columns are also different between the three files.

This is similar to my comment in the opening post: 
> There may need to be discussion for both the DISEASES and TISSUES apis on whether to keep the "channels" (assertions from different kinds of knowledge like manually curated knowledge vs experimental vs text-mined) in separate fields (tissues.knowledge vs tissues.text-mined)....

**Comment by colleenXu** [comment]
clarifying after talking with @andrewsu : separate records for each (same subject/object pair, but from different files)

**Comment by NikkiBytes** [comment]
I've added in the other species files that are available. 
Below are a couple of example records. Will push the data plugin to pending.api repo. 

<details>
<summary>Example Records</summary>

```    
[
    {
        "_id": "BTO:0001484",
        "subject": {
            "id": "BTO:0001484",
            "name": "Nervous system"
        },
        "association": {
            "source": "UniProtKB-RC",
            "expression": "CURATED",
            "confidence": 4.0,
            "category": "knowledge"
        },
        "object": {
            "ensembl": "ENSMUSP00000141169",
            "symbol": "Carf"
        }
    },
    {
        "_id": "BTO:0001066",
        "subject": {
            "id": "BTO:0001066",
            "name": "Hippocampal pyramidal layer"
        },
        "association": {
            "zscore": "6.633",
            "confidence": "3.316",
            "category": "textmining"
        },
        "object": {
            "ensembl": "ENSRNOP00000000008",
            "symbol": "Gad1"
        }
    }
]
```


</details>

**Comment by colleenXu** [comment]
@NikkiBytes @andrewsu perhaps the human files and other species files could be kept separate? Since Translator currently doesn't handle non-human stuff well...

and maybe the _id field can be a hash rather than the subject - since I imagine multiple records have the same subject...

---

And I don't know if this is possible...but could the records be kept separate by file (and species)? Something like this (modified from my desired example [here](https://github.com/biothings/pending.api/issues/26#issuecomment-995353582):

```
{
    "human": {
        "experiments": {
            "subject": {
                "DOID": "DOID:0060041",
                 "name": "Autism spectrum disorder"
            },
            "association": {
                "confidence": 0.835,
                "evidence": {
                    "p-value" : 7e-06
                },
                "source": "DistiLD"
            },
            "object": {
                "symbol": "MAP7",
                 "ensembl_protein": "ENSP00000482335"
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
just noting that these are just questions + suggestions, not required...

**Comment by andrewsu** [comment]
Based on my conversation with @NikkiBytes just now:

1. Let's process the human file only for now (later if we want to add the other organisms, we can add a node property as `object.organism`)
2. Need to fix the `_id` so that it is unique
3. Leave the "channel" type (e.g., "experiment", "knowledge", "text mining") under `association.category`

**Comment by colleenXu** [comment]
Note that in the current DISEASES api, it looks like there are symbols / names in the ensembl field. This is incorrect, since only ensembl IDs should be in that field...

Example: search "Y_RNA" in the records returned by this query
https://pending.biothings.io/diseases/query?q=DISEASES.associatedWith.ensembl:Y_RNA

**Comment by andrewsu** [comment]
updated the title to limit scope and bring us closer to closing this issue.

The relevant repo for the data plugin created by @NikkiBytes is at https://github.com/NikkiBytes/TISSUES.  The fix for at least point 1 from above (process human files only) has been [committed](https://github.com/NikkiBytes/TISSUES/commit/1391dc1673ad047fb8e71d69a9c2e2ef7428b039). I'm going to assign this to @erikyao to attempt creation of the API on the pending hub so we can see the current status.

**Comment by erikyao** [comment]
API published, https://biothings.ncats.io/tissues
