### ISSUE TITLE
fix slug for mrcoc API to "cooccurrence"

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#27]
Currently, http://pending.biothings.io/mrcoc generates example URLs like this:

http://pending.biothings.io/mrcoc/coocurence/D001055-D003397

These give a 404 error because the correct URL should be this (notice spelling change in coocurence / cooccurence )

http://pending.biothings.io/mrcoc/cooccurence/D001055-D003397

But as long as we are fixing things, we ideally would use the correct spelling to cooccurrence

http://pending.biothings.io/mrcoc/cooccurrence/D001055-D003397

**Comment by erikyao** [comment]
Let's define:

- "coocurence" the wrong spelling `S1` (as used in example URLs), 
- "cooccurence" the wrong spelling `S2` (as used in current API),  and
- "cooccurrence" the correct spelling `S3`

`S1` was introduced from the wrong "document type" of the mrcoc build, [https://studio.biothings.io/master/#/build/mrcoc_20200702_5dgmiatr](https://studio.biothings.io/master/#/build/mrcoc_20200702_5dgmiatr)

`S2` was probably specified as `ES_DOC_TYPE` as in [https://github.com/biothings/pending.api/blob/master/config_web/mrcoc.py#L4](https://github.com/biothings/pending.api/blob/master/config_web/mrcoc.py#L4).

I think a re-publication of this API, using `S3` for these attributes, would solve the issue.

**Comment by erikyao** [comment]
Fixed in [commit 861d034](https://github.com/biothings/pending.api/commit/861d03426f346c1ab703d3466ff3de15f360670c) and API re-published
