### ISSUE TITLE
create new API for gene-disease associations from AGR

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#28]
The Alliance for Genome Resources (AGR) maintains a list of gene-disease associations for seven organisms (including human, mouse, rat, fly, worm, zebrafish, and yeast) at https://www.alliancegenome.org/downloads.  Files can be downloaded in either JSON or TSV.  I don't think these data have been imported into any other biothings API.  They are candidates for inclusion in mygene.info and mydisease.info, but as a starting point we should create a pending API.  This would be incredibly useful for Translator...

**Comment by sierra-moxon** [comment]
'DBobjectType' in these files can be one of several values: 'gene', 'allele', 'affected genomic model'.
'DBobjectType' = 'gene' rows/objects are probably the ones you are looking for.

('affected genomic model' DBobjecType, is a grouping class for 'genotype', 'strain', 'population' or 'genotype + sequence targeting reagents like morpholinos, crisprs and talens'.  'affected genomic model' objects represent animal 'models of' a human disease).

If you need more information about how the gene->disease annotations are made (these are a result of curation at either the gene, allele, or affected genomic model levels), please do let me know.  Here's [one paper that describes MGI's approach](http://www.informatics.jax.org/mgihome/other/publications.shtml).

**Comment by tokebe** [comment]
Thank you, I've included filtering to only inlcude `'DBobjectType' == 'gene'` rows in the parser. I think I have it working, though please let me know if I missed anything. I just updated my PR with an example output document in case that's useful.

**Comment by erikyao** [comment]
Hi @tokebe, sorry we cannot deploy the new API due to some minor technical issue in the new biothings API v0.10 (see this [comment](https://github.com/biothings/pending.api/issues/22#issuecomment-899915757)). Will keep you updated. Thank you!

**Comment by erikyao** [comment]
It's published! Check https://pending.biothings.io/agr

Please let me know if you found anything wrong. Thank you!

**Comment by andrewsu** [comment]
looks good to me! @colleenXu can you create a new issue to create a smartAPI record for this new API?  prioritize as you see fit..

**Comment by colleenXu** [comment]
Added an issue about this here: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/260
