### ISSUE TITLE
Dockerize pending API web deployment

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#29]
Let's create a Docker deployment file for the production deployment:
* Required Elasticsearch server is hosted externally and provided via environment variables for the web API to connect and query.
* No need of Nginx, run just one tornado process within one container.
* Plan to deploy to both dev/stage and prod environment. Likely need to have a docker-compose file to include all required configurations for different settings.

**Comment by zcqian** [comment]
Is there a config.py that we can use as a reference?

**Comment by zcqian** [comment]
@newgene Is there a config.py that we can use as a reference?

**Comment by newgene** [comment]
@zcqian I believe we use `config_web` as the config module in production: `python index.py --conf config_web`

**Comment by zcqian** [comment]
Implemented in #33 
Awaiting deployment results

**Comment by zcqian** [comment]
#33 Merged
