### ISSUE TITLE
Update / fix MGIGene2Phenotype API

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#31]
Tasks:
- Fork the parser (rename to use biothings repo): https://github.com/kevinxin90/mgi_gene2phenotype
- update the parser and data for the API https://pending.biothings.io/mgigene2phenotype/
    - fix this: the mgi.has_homolog field either has the [value of "null"](https://pending.biothings.io/mgigene2phenotype) OR has the NCBIGene ID for the mouse gene (compare this [record](https://pending.biothings.io/mgigene2phenotype/gene/MGI:101816) to this [info](https://www.ncbi.nlm.nih.gov/gene/?term=17685)). These are "equivalent ids", not IDs for two different genes with the homolog relationship. 
    - Instead, the NCBIGene ID for the mouse gene should instead be in a field like **xrefs.ncbigene**

**Comment by andrewsu** [comment]
This issue is a lower priority (and this data resource is possibly obsolete) given the integration of AGR gene-disease phenotypes in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/260 and https://github.com/biothings/pending.api/issues/28.

**Comment by andrewsu** [comment]
as noted in the previous comment, going to close this issue in favor of https://github.com/biothings/biothings_explorer/issues/260 and https://github.com/biothings/pending.api/issues/28
