### ISSUE TITLE
Old cord_* APIs can be removed

### ISSUE THREAD

**Issue by bill-baumgartner** [biothings/pending.api#35]
The 10 cord_* APIs can be removed as they contain outdated data at this point. User should make use of the `text_mining_co_occurrence_kp` API instead.

cord_protein
cord_anatomy
cord_bp
cord_cc
cord_cell
cord_chemical
cord_disease
cord_gene
cord_genomic_entity
cord_ma

**Comment by erikyao** [comment]
Removed
