### ISSUE TITLE
Update Multiomics Wellness KP data plugin

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#36]
>Hi @Chunlei Wu (Exploring Agent, Service Provider) - We have new tsv files (v1.5) for the multiomics wellness KP. I've updated the parser and manifest file appropriately and tested a local deployment of the API using Biothings Studio. There are ~288,000 documents, so it's not huge. I believe the update should go smoothly. When you have some time, could you deploy the updated KG? Here's the repo with the parser and manifest file: https://github.com/Hadlock-Lab/multiomics_wellness_kp. Please let me know if you have any questions. We appreciate your help.

**Comment by erikyao** [comment]
Hi, @newgene and @colleenXu, it's updated. Please check https://pending.biothings.io/multiomics_wellness_kp. Let me know if I can be of any further assistance.

**Comment by colleenXu** [comment]
so next step is figuring out if the x-bte annotation needs updating based on what's in the new API...

**Comment by colleenXu** [comment]
@erikyao @newgene I believe a new version of data (I dunno if it includes the parser too) was sent out yesterday ~11 am PT. Has the API been updated to fit that?

**Comment by erikyao** [comment]
@colleenXu just updated!

**Comment by colleenXu** [comment]
@erikyao I'm a bit confused, I expected there to be subject.NCIT and object.NCIT fields (and indexing/search so I could query _exists_ on those fields).

**Comment by colleenXu** [comment]
@erikyao also I think the subject.CHEBI fields and object.CHEBI fields no longer have data...

**Comment by erikyao** [comment]
@colleenXu it's updated again. I didn't notice that the introduced changes in ES mapping from the last update so the new fields like `subject.NCIT` and `object.NCIT` were not exposed. 

After this update, queries below should work:

- https://pending.biothings.io/multiomics_wellness_kp/query?q=_exists_:subject.NCIT
- https://pending.biothings.io/multiomics_wellness_kp/query?q=_exists_:object.NCIT
