### ISSUE TITLE
Update `text_mining_cooccurrence_kp` source

### ISSUE THREAD

**Issue by erikyao** [biothings/pending.api#37]
From Edgar Gatica:

> I have finished making my changes to the cooccurrence text mining KP, which can be found here: https://github.com/UCDenver-ccp/text_mining_cooccurrence_kp
Unfortunately there isn’t currently any data in the prod DB for cooccurrence, so the files that dumper would copy and parser would read don’t yet exist. Hopefully that will be coming soon.
Relatedly, Bill asked me if I could get it to update more frequently, as he expects the databases to update daily once everything is running correctly. I modified the “dumper.schedule” attribute in the manifest to attempt to schedule it for the beginning of every day, rather than once weekly. I assumed it was syntax like cron, but if it isn’t (or if I need to do something else to change the schedule) please let me know.

**Comment by edgargaticaCU** [comment]
The data files referenced by this parser are now available, so it can be deployed.

**Comment by erikyao** [comment]
Deployed!
