### ISSUE TITLE
missing "code" metadata for semmeddb API

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#39]
https://biothings.ncats.io/semmeddb/metadata

does not include a "code" section, which cause this API page misses the "code" link.

v.s. other pending APIs, like this one:

https://biothings.ncats.io/semmed_anatomy/metadata at https://biothings.ncats.io/semmed_anatomy

Both are manifest based data plugins:

https://github.com/r76941156/semmed_parser
v.s.
https://github.com/kevinxin90/semmedana

**Comment by erikyao** [comment]
Fixed with Biothings API update.
