### ISSUE TITLE
update pending dgidb API

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#40]
BTE is using https://pending.biothings.io/dgidb quite a bit, and I believe it hasn't been updated since it was made (in 2018/2019?). 

We are interested in updating BOTH the parser + data for this API. This API is using the biolink-model predicates in the association.edge-label field....so we may want to remove this or map the dgidb relations to the most recent version of the biolink-model.

**Comment by andrewsu** [comment]
Before refreshing our pending API, @colleenXu, can you look at whether we can annotate their API for use within BTE directly? https://www.dgidb.org/api

**Comment by colleenXu** [comment]
We could theoretically annotate the interactions endpoint with x-bte annotation, but there are some issues...

* the `genes` field can accept Entrez IDs (not just gene symbols / names). However, the response will be under the `matchedTerms` field or `ambiguousTerms` field, depending on [how their API was able to match the search term](https://dgidb.org/api/v2/interactions.json?genes=23654,2321) (and I don't see a clear pattern for when it'll do one vs the other). At the moment, to handle looking at two different response-mappings, we'd need duplicate operations / sub-queries...
* the `drugs` field expects [names](https://dgidb.org/api/v2/interactions.json?drugs=CEDIRANIB). I've tried inputting chembl ID [in](https://dgidb.org/api/v2/interactions.json?drugs=CHEMBL:CHEMBL491473) [different](https://dgidb.org/api/v2/interactions.json?drugs="chembl:CHEMBL491473") [ways](https://dgidb.org/api/v2/interactions.json?drug=CHEMBL491473) and haven't been successful in getting the record out
* This API is slower than a BioThings API would be (takes ~ 7 sec to [return 1 gene's interactions](https://dgidb.org/api/v2/interactions.json?genes=2321)) and likely has less capacity for batch-querying (it can accept a comma-delimited list for a GET parameter and the documentation says POST is possible)

**Comment by colleenXu** [comment]
noting current parser issues:

    some chem may have incorrectly imported IDs (have a wikidata ID and a non-matching CHEMBL ID in the object.id field...)
    the relationships in DGIdb are drug -> gene, but the API is set up with subject as gene and object as chem

**Comment by erikyao** [comment]
Hi @colleenXu, could you please double check the mapping from DGIdb interaction types to Biolink predicates?

Within the DGIdb Feb 2022 [interactions.tsv](https://www.dgidb.org/data/monthly_tsvs/2022-Feb/interactions.tsv), the `interaction_types` column has values like `inhibitor`, `blocker`, etc. My understanding is that, e.g. with `blocker`, we can find in [biolink-model.yaml](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml) that `DGIdb:blocker` is one of the `narrow_mappings` of predicate `decreases activity of`. Therefore we map the `blocker` interaction type to `decreases_activity_of` (whitespaces replaced by underscores) predicate. 

Please correct me if I am wrong.

**Comment by colleenXu** [comment]
@erikyao @andrewsu My understanding is that we don't need to map from DGIdb interaction types to Biolink predicates in the API....this can be handled in the x-bte annotation. 

In the past, Kevin had included this mapping in the parser for some reason...

**Comment by erikyao** [comment]
Hi @andrewsu @colleenXu , the latest DGIdb Feb 2022 [interactions.tsv](https://www.dgidb.org/data/monthly_tsvs/2022-Feb/interactions.tsv) has a new column `interaction_group_score`, which is actually the "Interaction Score" as explained [here](https://www.dgidb.org/score).

E.g. the interaction between [BMS-387032](https://www.dgidb.org/drugs/BMS-387032) and [CDK7](https://www.dgidb.org/genes/CDK7) has a score of 0.82, as shown [here](https://www.dgidb.org/interactions/4b8fe03c-c9bd-49ae-bb59-eb6cb28cc9ea#_summary).

Shall we integrate these scores into a field, say `association.score`? Thanks!

**Comment by erikyao** [comment]
Hi @colleenXu, w.r.t.

> * some chem may have incorrectly imported IDs (have a wikidata ID and a non-matching CHEMBL ID in the object.id field...)

I noticed that in the tsv file they have revised the column name from `drug_chembl_id` to `drug_concept_id`, whose values include:

1. empty values
2. wikidata IDs in the form of `wikidata:Q<num>`, such as `wikidata:Q419808` for `SAPROPTERIN`
3. ensembl IDs in the form of `chembl:CHEMBL<num>`, such as `chembl:CHEMBL942` for `BISACODYL`

I'll query MyGene with drug names for case 1 and case 2, to solve the `wikidata` problem.

Could you explain more on `a non-matching CHEMBL ID in the object.id field`? Thank you!

-----

W.r.t.

> * the relationships in DGIdb are drug -> gene, but the API is set up with subject as gene and object as chem

I'll swap `object` and `subject` fields in the parser.

**Comment by colleenXu** [comment]
#### On the wikidata vs chembl.compound IDs
I don't quite remember what was going on, and I can't find an example in the current API. My guess is that every record in the current API has an object.CHEMBL_COMPOUND field, and I found some wikidata IDs in that field for some records...

To clarify: 
* I'm not sure what you mean by "ensembl ids" here. It sounds like you're dealing with CHEMBL IDs? specifically CHEMBL.COMPOUND IDs? And you'd query MyChem rather than MyGene?
* are you mapping drug names (when the drug_concept_id field is empty) and drug wikidata IDs (when the drug_concept_id is a wikidata ID) to CHEMBL.COMPOUND ids - so the final biothings API only has chembl.compound IDs for chemicals? that'd be awesome

#### the column-to-field table

I'd like to keep the tsv column names in some cases....
* column index 3: association.interaction_claim_source 
* column index 4: association.interaction_types
* column 7: subject.drug_name
* column 10: association.pmids

**Comment by colleenXu** [comment]
Also, my understanding has been that:
* subject.id has the prefix-id combo (CHEMBL.COMPOUND:1234) while subject.CHEMBL_COMPOUND would only have the ID (1234)
* same with object.id (NCBIGene:1234) vs object.NCBIGene (1234)

However, the BTE tool seems to be doing fine with prefixed or non-prefixed IDs for those ID-namespaces/prefixes right now...

**Comment by erikyao** [comment]
> * I'm not sure what you mean by "ensembl ids" here. It sounds like you're dealing with CHEMBL IDs? specifically CHEMBL.COMPOUND IDs? And you'd query MyChem rather than MyGene?

Sorry it's a typo. I mean chembl ids actually. And it's MyChem.

> * are you mapping drug names (when the drug_concept_id field is empty) and drug wikidata IDs (when the drug_concept_id is a wikidata ID) to CHEMBL.COMPOUND ids - so the final biothings API only has chembl.compound IDs for chemicals? that'd be awesome

yes, that's what I am going to do.

> The current parser keeps the CHEMBL.COMPOUND prefix on both fields of the object (id + CHEMBL_COMPOUND) right now...

I can fix this issue as well.

**Comment by erikyao** [comment]
@colleenXu, and since we are going to remove the mapped predicates, the `association.edge_label` field is to be removed. Originally we have set it at [parser.py#L122](https://github.com/biothings/DGIdb/blob/master/parser.py#L122)

**Comment by erikyao** [comment]
https://biothings.ncats.io/dgidb updated

**Comment by colleenXu** [comment]
@erikyao it looks like the field name suggestions [here](https://github.com/biothings/pending.api/issues/40#issuecomment-1094189354) weren't addressed...what were your thoughts?

**Comment by colleenXu** [comment]
@erikyao also, I see many records without an association.relation_name field....it would help to give these records some kind of value. I see "n/a" and "other/unknown" interaction types in https://dgidb.org/interaction_types....so it would help to maybe keep these values, as not_applicable and other_unknown....

**Comment by colleenXu** [comment]
updated x-bte annotation for dgidb. still have the issues noted above https://github.com/NCATS-Tangerine/translator-api-registry/commit/03074911b5f2321514f27704b904bf8d1352e7ee

**Comment by erikyao** [comment]
> ### the column-to-field table
> I'd like to keep the tsv column names in some cases....
> 
> * column index 3: association.interaction_claim_source
> * column index 4: association.interaction_types
> * column 7: subject.drug_name
> * column 10: association.pmids

Revised as suggested

**Comment by erikyao** [comment]
> @erikyao also, [most of the API records seem to not have an association.relation_name field](https://pending.biothings.io/dgidb/query?q=NOT%20_exists_:association.relation_name)....it would help to give these records some kind of value. Right now BTE cannot get these associations...
> 
> I see "n/a" and "other/unknown" interaction types in https://dgidb.org/interaction_types so it would help to maybe keep these values. Maybe by having the values `not_applicable` and `other_unknown`....

`not_applicable` is used for empty interactions

**Comment by colleenXu** [comment]
These are the interaction_types in the raw data. I've noted the ones that I commented out the x-bte annotation for, because there were only a few records for the operation...

* activator
* agonist
* allosteric_modulator
* antagonist
* antibody
* *antisense_oligonucleotide: commented out, only 4 records*
* blocker
* *inducer: commented out, only 1 record*
* inhibitor
* *inhibitory_allosteric_modulator: commented out, only 1 record*
* inverse_agonist
* modulator
* *negative_modulator: commented out, only 5 records*
* not_applicable (as mentioned [above](https://github.com/biothings/pending.api/issues/40#issuecomment-1098572483), a lot of rows had no value for interaction_types...)
* partial_agonist
* positive_modulator
* *suppressor: commented out, only 1 record*
* *vaccine: commented out, only 8 records*
