### ISSUE TITLE
update ontology apis?

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#42]
However, we may be able to annotate ontology lookup service [(website)](https://www.ebi.ac.uk/ols/index) [(smartapi entry)](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/ols/smartapi.yaml) to retrieve this kind of information?

The following [pending](https://pending.biothings.io/) BioThings APIs are used by BTE (but aren't called upon often):
* Gene Ontology Biological Process API
* Gene Ontology Cellular Component API
* Gene Ontology Molecular Activity API
* Human Phenotype Ontology API
* UBERON Ontology API

**Comment by andrewsu** [comment]
Given completion of https://github.com/biothings/biothings_explorer/issues/196, I think we handle the most critical ontologies in terms of subclass relationships.  Let's create new issues if there are specific relationships that we want to add.
