### ISSUE TITLE
New EBI G2P gene2phenotype API

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#5]
EBI gene2phenotype (https://www.ebi.ac.uk/gene2phenotype)

EBI gene2pheontype (or G2P) is a knowledge source providing human-curated gene-to-disease associations with a focus on cancer and developmental disease areas. Each G2P entry associates an allelic requirement and a mutational consequence at a defined locus with a disease entity. A confidence level and evidence link are assigned to each entry. The data file is available to download at:

https://www.ebi.ac.uk/gene2phenotype/downloads.

**Comment by kevinxin90** [comment]
Done:

[Project repo](https://github.com/kevinxin90/ebi_data_parser)
[SmartAPI query interface](http://smart-api.info/ui/1f47552dabd67351d4c625adb0a10d00)
[Pending API site](https://pending.biothings.io/ebigene2phenotype)
[SmartAPI annotation file](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/EBIgene2phenotype/smartapi.yaml)
