### ISSUE TITLE
Animation errors in the index page when switched to Vuex 3.6.2

### ISSUE THREAD

**Issue by erikyao** [biothings/pending.api#52]
![image](https://user-images.githubusercontent.com/4813680/152880641-12f29ac0-5944-4e74-892b-f59e973ddf03.png)

Related issue: https://github.com/biothings/pending.api/issues/50

We have switched to Vuex 3.6.2 so some animation code may not work anymore. A downgrade to an older v3 version could be a quick fix.

**Comment by marcodarko** [comment]
@erikyao I can't replicate this on my local but I think I know why.  The transitions for each section hide the animation container until it's into view.  So initially you might see this but this doesn't cause any issues for the animation, it still runs fine when you scroll to that section it just rerurns. 
I have removed such scrolling animation on that container so it's visible at load time.  this change is here: https://github.com/biothings/pending.api/tree/fix-ani-err

However like I said, I can't seem to be able to replicate it but I'm somewhat confident this is why. Also this doesn't break anything but if you want to get rid of that ugly red log feel free to try it. 

I'll keep trying to replicate it but all I see is an internal error from one of the libraries (content.js) which is fine, it's a big auto generated Adobe Animation file I don't wanna mess with.

**Comment by erikyao** [comment]
Hi @marcodarko, your fix works in my test env. I am going to make a PR
