### ISSUE TITLE
Create API for SuppKG (Dietary Supplements)

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#55]
SuppKG contains a variety of edges for Dietary Supplements.

Publication: https://arxiv.org/abs/2106.12741
Download link: https://github.com/zhang-informatics/SemRep_DS/tree/main/SuppKG

There are 595222 entries under the `links`.  Here is one example record:

```
        {
            "relations": [
                {
                    "pmid": 1394115,
                    "sentence": "Turmeric and curcumin were also found to reverse the aflatoxin induced liver damage produced by feeding aflatoxin B1 (AFB1) (5 micrograms/day per 14 days) to ducklings.",
                    "conf": 0.9303833842,
                    "tuid": 0
                },
                {
                    "pmid": 1394115,
                    "sentence": "Reversal of aflatoxin induced liver damage by turmeric and curcumin.",
                    "conf": 0.9396179318000001,
                    "tuid": 0
                }
            ],
            "source": "C0001734",
            "target": "C0151763",
            "key": "CAUSES"
        },
```

I believe we want to create a record like this (where the info for `name` can be found in the `nodes` section of the json).

```
{
    "_id": "C0001734_C0151763_CAUSES",
    "subject": {
        "umls": "C0001734",
        "name": "aflatoxin",
        "semtypes": [ "bacs", "hops"]
    },
    "relation": [
        {
            "pmid": 1394115,
            "sentence": "Turmeric and curcumin were also found to reverse the aflatoxin induced liver damage produced by feeding aflatoxin B1 (AFB1) (5 micrograms/day per 14 days) to ducklings.",
            "conf": 0.9303833842,
            "tuid": 0
        },
        {
            "pmid": 1394115,
            "sentence": "Reversal of aflatoxin induced liver damage by turmeric and curcumin.",
            "conf": 0.9396179318000001,
            "tuid": 0
        }
    ],
    "object": {
        "umls": "C0151763",
        "name": "damage liver",
        "semtypes": [ "patf" ]
    },
    "predicate": "CAUSES"
}
```

**Comment by colleenXu** [comment]
Pasted from Slack, my notes after reviewing the output file from: 
> an open source contributor created this parser https://github.com/mnarayan1/suppkg-data/blob/main/parser.py to address this ticket https://github.com/biothings/pending.api/issues/55. The sample output file is at https://drive.google.com/file/d/1qsPvQre8E4Cz0JqvLR44A8vMuJz57VAq/view?usp=sharing

I think the structure is okay for writing queries with x-bte annotation. 
But....

Point 0: I wonder if the relation array ever gets a LOT of elements

Point 1: Looking at the output file, some umls IDs seem to start with "DC" which seems incorrect. It looks like the "D" should be removed, so the ID starts with "C". Examples:
* D[C1029148](https://uts.nlm.nih.gov/uts/umls/searchResults?searchString=C1029148) (from the idx 1 record)
* D[C0016163](https://uts.nlm.nih.gov/uts/umls/searchResults?searchString=C0016163) (from the idx 7 record)

Point 2: Looking at the output file, some IDs don't seem to match their names. Examples:
* the idx 2 record has object.name as "aceite niauli". I'm not sure what that means. The object.umls  is DC0028908. After removing the "D" (see point 1), [this ID](https://uts.nlm.nih.gov/uts/umls/searchResults?searchString=C0028908) corresponds with "oils".
* the idx 6 record has object.name as "genotoxins". However, the corresponding ID's official name is [mutagens](https://uts.nlm.nih.gov/uts/umls/concept/C0026879) (genotoxins does show up as an "atom" underneath, likely a cross-mapped ID).

Point 3: Looking at the output file, some semantic types don't exist or don't seem to match the ID given
I'm seeming "dsp" in object.semtypes (idx 2, idx 7 records) and this isn't a UMLS abbreviation (they're always 4 letters)
the idx 7 record has object.umls: D[C0016163](https://uts.nlm.nih.gov/uts/umls/searchResults?searchString=C0016163), which seems to refer to "fishes". However, the object.semtypes are imft (Immunologic Factor) and "dsp". Which seems odd.
the idx 9 record has D[C1140671](https://uts.nlm.nih.gov/uts/umls/searchResults?searchString=C1140671), which seems to refer to "rice / Oryza sativa". However, its semtypes are orch (organic chemical) and phsu (pharmacological substance). Again, odd.

**Comment by colleenXu** [comment]
From reading the preprint, it sounds like they made some pseudo-UMLS IDs from "iDISK terms" that didn't map to an existing CUI....is that right? And that some of these "iDISK terms" were drug supplement ingredients...This makes me wonder about the MRCONSO.RRF file that they mention, which sound like it may have mappings from the original "iDISK terms" to pseudo-UMLS IDs used in their KG...

Also, it sounds like they put "phsu" as the semantic type for all drug supplements for their work, even if the original UMLS ID isn't considered a Pharmacological Substance. This makes me think of the plant terms (Point 3 / bullet 2 in my above post). 

They also mention a networkx file and I wonder if that's useful...

**Comment by erikyao** [comment]
> (from looking at the materials + method section of the preprint)
> 
> It sounds like the authors made some pseudo-UMLS IDs from "iDISK terms" that didn't map to an existing CUI....is that right? And that some of these "iDISK terms" were drug supplement ingredients...This makes me wonder about the MRCONSO.RRF file that they mention, which sound like it may have mappings from the original "iDISK terms" to pseudo-UMLS IDs used in their KG...
> 
> Also, it sounds like they put "phsu" as the semantic type for all drug supplements for their work, even if the original UMLS ID isn't considered a Pharmacological Substance. This makes me think of the plant terms (Point 3 / bullet 2 in my above post).
> 
> They also mention a networkx file and I wonder if that's useful...

Hi @colleenXu , from [SemRep_DS/docs/SemRep_full_fielded_output.txt](https://github.com/zhang-informatics/SemRep_DS/blob/main/docs/SemRep_full_fielded_output.txt):

> *_CUI: The CUI of the subject/object entity. If a CUI starts with
'DC' instead of just 'C' it is an iDISK CUI and is not present in the UMLS.

**Comment by andrewsu** [comment]
@erikyao deployed the API based on the parser written by @mnarayan1 (https://github.com/biothings/SuppKG).  @colleenXu can you add creation of the smartAPI annotation to your to-do list please?  ("Normal" priority -- no special urgency here...)

Let's also leave this ticket open for the moment so we can contemplate enhancements to the parser (for example, to handle retired UMLS IDs, get more current human-readable names and semtypes, etc)...

**Comment by colleenXu** [comment]
Related to https://github.com/NCATS-Tangerine/translator-api-registry/pull/122

**Comment by colleenXu** [comment]
Closing in favor of https://github.com/biothings/biothings_explorer/issues/706
