### ISSUE TITLE
evaluate Therapeutic Target Database (TTD) as data source

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#57]
Evaluate Therapeutic Target Database (TTD) as a potential new API -- does this have new information that is not in an existing API, or is it an aggregator of resources we already have access to within mychem or BTE?

paper: https://pubmed.ncbi.nlm.nih.gov/34718717/
example record: http://idrblab.net/ttd/data/drug/details/d0s9mc
Downloads: http://db.idrblab.net/ttd/full-data-download

**Comment by colleenXu** [comment]
Also not sure how to handle the github issue assignment stuff here. For now, moving the pending repo issue to Yao's section of the project manager for Translator...
