### ISSUE TITLE
New API for MGI mouse gene2phenotype 

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#6]
MGI mouse gene2phenotype (http://www.informatics.jax.org/phenotypes.shtml)
MGI provides comprehensive annotations for mouse genes, including their phenotype and disease associations. By mapping mouse genes to their human orthologs, mouse phenotypes to human phenotypes, these associations provide insightful links between human genes and phenotypes. The multiple phenotype-related data files are available to download at 
http://www.informatics.jax.org/downloads/reports/index.html#pheno.

**Comment by kevinxin90** [comment]
Done:

[Project repo](https://github.com/kevinxin90/mgi_gene2phenotype)
[SmartAPI query interface](http://smart-api.info/ui/77ed27f111262d0289ed4f4071faa619)
[Pending API site](https://pending.biothings.io/mgigene2phenotype)
[SmartAPI annotation file](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/MGIgene2phenotype/smartapi.yaml)
