### ISSUE TITLE
Data source: BioPlanet

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#60]
https://tripod.nih.gov/bioplanet/#

seems to be a valuable resource for gene sets and pathway-disease mappings.  This was suggested by an SME from the Translator project as a reputable source of pathway information.

![image](https://user-images.githubusercontent.com/2635409/156851548-f5e95c68-7537-4fce-be15-6524951a8c56.png)

**Comment by andrewsu** [comment]
assigned to @rjawesome

**Comment by erikyao** [comment]
Hi @rjawesome, this could be a manifest-based plugin, and you can start with a vanilla parser module. See https://docs.biothings.io/en/latest/tutorial/studio_guide.html#manifest-based-data-plugins for more.

**Comment by rjawesome** [comment]
The requested changes have been completed

**Comment by erikyao** [comment]
Deployed:

- https://biothings.ncats.io/bioplanet_pathway_gene
- https://biothings.ncats.io/bioplanet_pathway_disease

Our internal `pending.api` hub has introduced some code changes and is under testing. I cannot make these two APIs shown on the index page. (otherwise it would be 44 APIs in total but now it’s 42). However they are accessible and you can have a try.

**Comment by colleenXu** [comment]
Should be done once BTE-trapi repo changes have been deployed to all instances

Registry related commits / PRs:
* https://github.com/NCATS-Tangerine/translator-api-registry/commit/050a5e9e9bc6b3991d72d1f63ddfd2447c8aaa28
* https://github.com/NCATS-Tangerine/translator-api-registry/commit/544d004695361b90aada2d208e711310579ec02e
* https://github.com/NCATS-Tangerine/translator-api-registry/pull/91
* https://github.com/NCATS-Tangerine/translator-api-registry/commit/0395669dfee9685031f6f5fdbe5d3ac383959bed

Related SmartAPI registrations:
* http://smart-api.info/registry?q=55a223c6c6e0291dbd05f2faf27d16f4
* http://smart-api.info/registry?q=b99c6dd64abcefe87dcd0a51c249ee6d

Related bte-trapi commit:
* https://github.com/biothings/BioThings_Explorer_TRAPI/commit/4c1e4fad357e0bf834a9bf8e0a72138fae26220a

**Comment by andrewsu** [comment]
Example query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                      "OMIM:167000"
                    ],
                    "categories": [
                      "biolink:Disease"
                    ]
                },
                "n1": {
		             "categories":[
                         "biolink:Pathway"
                        ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n1",
                    "object": "n0"
                }
            }
        }
    }
}
```

Example output: https://arax.ncats.io/?r=1212d872-8945-439a-84aa-f1f2a5ef6089

![image](https://user-images.githubusercontent.com/2635409/184189039-058a76fd-7834-4e03-9720-3928942efa87.png)
