### ISSUE TITLE
update data in PFOCR API

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#64]
In [this comment](https://github.com/wikipathways/pathway-figure-ocr/issues/16#issuecomment-1089329986), @ariutta describes an update to the data output from PFOCR.  We should accordingly update the PFOCR API available at https://biothings.ncats.io/pfocr.  Since this would greatly enhance (and possibly accelerate) the effort described in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/420, this issue has a slightly higher-than-normal priority.

Note that the current PFOCR parser is at https://github.com/kevinxin90/pfocr.  While we do the data update, we should also fork this repo into the github biothings organization and update the API metadata.

Note also that since the new file does not contain `associatedWith.pmid`, mentions of that in the parser should probably be replaced with `associatedWith.pmc`.

**Comment by erikyao** [comment]
Plugin forked to https://github.com/biothings/pfocr

API updated: https://biothings.ncats.io/pfocr

@andrewsu shall we change the version number from `2.0` to `3.0`, or some number else?

**Comment by andrewsu** [comment]
Unless @ariutta says there is some official version number that they use, let's just go with the date as the version number -- 2022-04-05. Thanks!

**Comment by erikyao** [comment]
Version number updated!
