### ISSUE TITLE
Data source: FoodData Central

### ISSUE THREAD

**Issue by andrewsu** [biothings/pending.api#66]
From the website (https://fdc.nal.usda.gov/index.html):

> FoodData Central is an integrated data system that provides expanded nutrient profile data and links to related agricultural and experimental research.

Like FooDB (https://github.com/biothings/pending.api/issues/65), this FoodData Central resource could provide edges between foods (indexed by the FoodOn ontology), and chemical compounds (though I do not see an obvious external identifier). For example, https://fdc.nal.usda.gov/fdc-app.html#/food-details/748366/nutrients shows the link between soybean oil and beta-sitosterol. 

Data can be downloaded in JSON format at https://fdc.nal.usda.gov/download-datasets.html. As of today, the most recent dataset is from Oct 2021.  According to the [licensing statement](https://fdc.nal.usda.gov/api-guide.html#bkmk-5), "USDA food composition data are in the public domain and they are not copyrighted. No permission is needed for their use. "

**Comment by rjawesome** [comment]
Parser: https://github.com/rjawesome/FoodData_parser/
Sample Document:
```json
{
    "subject": {
      "description": "Oil, soybean",
      "ndbNumber": 4044,
      "fdcId": 748366,
      "foodCategory": "Fats and Oils"
    },
    "object": {
      "nutrientName": "Beta-sitosterol",
      "nutrientId": 1288,
      "nutrientRank": 16200,
      "nutrientAmount": 153,
      "nutrientAmountUnits": "mg"
    },
    "relation": {
      "code": "A",
      "sourceCode": "1",
      "description": "Analytical",
      "sourceDescription": "Analytical or derived from analytical",
      "nutrientMinAmount": 152
    },
    "_id": "748366-1288"
  }
  ```

**Comment by andrewsu** [comment]
@rjawesome can you tell me how many unique objects (nutrients / chemicals) there are in the entire data set?  As noted above and confirmed by you, it doesn't look like there are any obvious external identifiers that can be used to link nutrients in this data source to other data sources.  But when I look at the record for soybean oil https://fdc.nal.usda.gov/fdc-app.html#/food-details/748366/nutrients, I only see a ~30 nutrients listed.  If that's all the nutrients that are in the entire data set, then we should spend the time to just map those by hand to some external vocabulary (like ChEBI, ChEMBL, PubChem, etc.). For example, ChEBI IDs for the various tocopherols can be found relatively easily here https://www.ebi.ac.uk/chebi/advancedSearchFT.do?searchString=Tocopherol

**Comment by rjawesome** [comment]
In total there are ~200-300 nutrients, although I don't know if all of them would map to an external vocabulary. (Also right now I am only using foundation foods).

**Comment by andrewsu** [comment]
Hmm, a couple hundred isn't so bad.  I suggest posting that list in a google doc (sorted by the number of foods that have data for each nutrient, if possible), and then we can spend a little time to do the manual mapping.  Automation would be useful if we had thousands, but for now, I think just searching in ChEBI, ChEMBL, and PubChem (in that order) and looking for exact string matches is probably the quickest route.  And no problem if some nutrients just don't map to any of those chemical databases...

**Comment by rjawesome** [comment]
https://docs.google.com/spreadsheets/d/1xZNt70XhyWpVOUkrTY2-gUqAYKI-_ONY4y2CR59AZGk/edit?usp=sharing. This contains the list of nutrients and # of occurences.

**Comment by andrewsu** [comment]
@rjawesome in your doc linked above, I created a new column for ChEBI.  (I also created columns for "ChEMBL" and "PubChem", but I think probably ChEBI will be sufficient.)  I think the next step is to add mappings when they can be easily found.  As mentioned above, you _could_ do the mapping by hand by searching on the [ChEBI website](https://www.ebi.ac.uk/chebi/). Or you could do a semi-automated run by doing exact string matching to `chebi.name` in mychem.info (e.g., http://mychem.info/v1/query?q=chebi.name:lactose&fields=chebi).  I think if we can get the ~75% that is easy to map in a lookup table that can be included with the data plugin/parser, that would be good enough.

**Comment by rjawesome** [comment]
@andrewsu I was doing some manual lookups on CHEBI and I was able to find about half of them (so far), but mainly I was not sure how to lookup the ones in the format of SFA/MUFA/TFA number:number, (ie. SFA 7:0). If you know how I could look those up on CHEBI or some other ID, I think I should be able to get most of them.

**Comment by rjawesome** [comment]
I got around 70% of the IDs, and added the chebi IDs to the parser under object.chebiId

**Comment by rjawesome** [comment]
@andrewsu is there anything else to finish for this parser? New sample doc below
```json
{
    "subject": {
      "description": "Oil, canola",
      "ndbNumber": 4582,
      "fdcId": 748278,
      "foodCategory": "Fats and Oils"
    },
    "object": {
      "nutrientName": "Beta-sitosterol",
      "nutrientId": 1288,
      "nutrientRank": 16200,
      "chebiId": "CHEBI:27693",
      "nutrientAmount": 368,
      "nutrientAmountUnits": "mg"
    },
    "relation": {
      "code": "A",
      "sourceCode": "1",
      "description": "Analytical",
      "sourceDescription": "Analytical or derived from analytical",
      "nutrientMinAmount": 352,
      "nutrientMaxAmount": 376,
      "nutrientMedianAmount": 371
    },
    "_id": "748278-1288"
  }
  ```

**Comment by andrewsu** [comment]
Looks good to me!  I think we can hand the data plugin off to @erikyao to deploy, and in parallel, you can get started on the SmartAPI annotation...

**Comment by rjawesome** [comment]
Ok, also just noting that records without chebi ids are excluded

**Comment by rjawesome** [comment]
Also just realized that the documents are missing foodon IDs, and they seem to not be on the json and only on their website, so I'm not sure where they are getting them from?

**Comment by andrewsu** [comment]
The options as I see them:

1. load as-is without FoodOn IDs
2. find contact info and ask them to add that mapping
3. web scrape that info from the website

I think you can go ahead with option 1, and look at the feasibility of 2 and 3 in parallel...

**Comment by rjawesome** [comment]
After some further investigation, I found the info was in their CSV but not JSON, so I can probably get the foodon data from their food attributes CSV which maps fdc id --> foodon link (which can be parsed to get food on id). Apparently, it seems the foodAttributes are just an empty array in the json so they must have some problem there.

**Comment by rjawesome** [comment]
Alright, I have edited the parser to add foodOn ids. new sample doc:
```json
"748278-1288": {
    "subject": {
      "description": "Oil, canola",
      "ndbNumber": 4582,
      "fdcId": 748278,
      "foodOnId": "FOODON_03302578",
      "foodCategory": "Fats and Oils"
    },
    "object": {
      "nutrientName": "Beta-sitosterol",
      "nutrientId": 1288,
      "nutrientRank": 16200,
      "chebiId": "CHEBI:27693",
      "nutrientAmount": 368,
      "nutrientAmountUnits": "mg"
    },
    "relation": {
      "code": "A",
      "sourceCode": "1",
      "description": "Analytical",
      "sourceDescription": "Analytical or derived from analytical",
      "nutrientMinAmount": 352,
      "nutrientMaxAmount": 376,
      "nutrientMedianAmount": 371
    },
    "_id": "748278-1288"
  }
```
Note that the documents decreased slightly from ~7000 to ~6000 (after filtering only for records which have foodon)

**Comment by colleenXu** [comment]
Noting that I'm not sure what the FoodOn ID format is (should it just be numeric? or does it have to have the "FOODON_" part?)

**Comment by andrewsu** [comment]
For the moment, let's just leave the foodOn data as proposed above `"foodOnId": "FOODON_03302578"`.  FoodOn is not an identifier that is currently used for data integration across resources in BTE, so for now it's simplest if we just use the format used in the data source.  Later, when/if FoodOn becomes more widely used in the BTE KG, we can discuss the identifier formatting in more detail....

**Comment by rjawesome** [comment]
Alright, I think that this is ready for deployment then
