### ISSUE TITLE
New API for DISEASES

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#7]
DISEASES (http://diseases.jensenlab.org/)
DISEASES is a weekly updated web resource that integrates evidence on disease-gene associations from automatic text mining, manually curated literature, cancer mutation data, and genome-wide association studies. It also provides confidence scores across supporting evidence which can be used to further compare or filter the different types and sources of evidence. Two data files (associations with full evidence and filtered list of unique associations) are available at https://diseases.jensenlab.org/Downloads.

**Comment by kevinxin90** [comment]
Done:

[Project repo](https://github.com/kevinxin90/DISEASES)
[SmartAPI query interface](http://smart-api.info/ui/a7f784626a426d054885a5f33f17d3f8)
[Pending API site](https://pending.biothings.io/DISEASES)
[SmartAPI annotation file](https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/DISEASES/smartapi.yaml)
