### ISSUE TITLE
"code" link standard

### ISSUE THREAD

**Issue by erikyao** [biothings/pending.api#73]
From @andrewsu :

> Also, as we get more people contributing parsers, what do you think about pointing the "code" link at a fork of the repo in the biothings github org as a general procedure?

**Comment by erikyao** [comment]
My 2 cents:

Pros of forking plugin repos into BioThings org:

- Easier and quicker to make changes on our side.
- May keep the repo well maintained. 
- No danger of repo deletion by 3rd-party.

Cons:

- Too many repos (44 at most now), difficulty in management? (FYI we can tag those repos).
- Changes by 3rd-party developers/organizations must be introduced through Pull Requests.
- Some organizations may prefer the links pointing to there own repos.

**Comment by andrewsu** [comment]
Great points, Yao.  Perhaps I'd modify my suggestion to say that we should do this practice only for APIs created by lab members (including interns).  For APIs hosted by third-party data owners, the code should absolutely point to their own repo.

**Comment by erikyao** [comment]
Reasonable. So I'll fork the two BioPlanet plugin repos into BioThing org later today.

I remember that there are some other plugin repos under my name (forked from Kevin's previously). So I can check later and start another issue to record the migration into BioThings org.

**Comment by colleenXu** [comment]
Noting that plenty of pending apis currently post to someone's repo (example [Kevin](https://pending.biothings.io/DISEASES) and [me](https://pending.biothings.io/multiomics_wellness_kp)).

I'm good with whatever decision the rest of you make. I don't know much about this topic...

**Comment by newgene** [comment]
A new [biothings_data_plugins](https://github.com/biothings/biothings_data_plugins) created for long-term hosting of our data plugins. We can move a data plugin over when it's mature and no more major changes.

See this biomuta plugin example:

https://github.com/biothings/biothings_data_plugins/tree/main/b/biomuta

and how it's used in "pending.api" data hub:

https://github.com/biothings/pending.api/blob/master/plugins/biomuta
(as a link created via `ln -s ../../biothings_data_plugins/b/biomuta .` under the `plugins` folder)
