### ISSUE TITLE
web ui: API page should display failed queries output too

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#75]
related to #74, when an example query fails, we should still display it in the UI, including its status code.

For example this failed query from #74:

https://biothings.ncats.io/rhea/query?q=citations:PMID:18949503

from:

https://biothings.ncats.io/rhea/

**Comment by marcodarko** [comment]
Will be addressed in https://github.com/biothings/pending.api/pull/78

**Comment by andrewsu** [comment]
I believe this is the intended behavior (as opposed to showing a blank box), so closing this issue... 

![Image](https://github.com/biothings/pending.api/assets/2635409/6558fffb-f733-495a-9b4d-a4ef00794b09)
