### ISSUE TITLE
Implement setwise NGD

### ISSUE THREAD

**Issue by erikyao** [biothings/pending.api#79]
# Design of Setwise NGD Implenetation

## 1. Previous Work & New Requirements

- Previous (vanilla) NGD requirements: [BioThings_Explorer_TRAPI - Issue#326](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/326) 
- Previous (vanilla) NGD implementation: finalized at [pending.api - commit 2ccd0e2](https://github.com/biothings/pending.api/commit/2ccd0e2a7f68b2e8d4beff3df1610d6ca09bdce2)
- New **setwise** NGD requirements: [BioThings_Explorer_TRAPI - Issue#459](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/459)

### 2.1 Vanilla Document Frequencies

The documents in our application are of associations/interactions, which contains a _subject_ and an _object_ field.

Given a set of such documents (a.k.a. a corpus in Information Retrieval) `S`, the (vanilla) set of documents containing a term `x` can be defined

$$
S(x) = \lbrace d \mid d.subject \text{ contains } x \text{ OR } d.object \text{ contains } x\rbrace.
$$

The **document frequency** of term `x` is the size of the documents containing it, i.e. 

$$
f(x) = \vert \vert S(x) \vert \vert.
$$

We call such a document frequency a **unary document frequency** since there is only one term `x` to match either side, _subject or object_.

When a pair of terms is considered, we can expand our definitions to a **bipartite** degree, which describes the scenario of two terms matching to both sides, _subject and object_, respectively. I.e. the set of documents containing a term pair `(x, y)` is

$$
\begin{aligned}
S(x, y) = \lbrace d \mid & (d.subject \text{ contains } x \text{ AND } d.object \text{ contains } y) \text{ OR } \newline 
                         & (d.subject \text{ contains } y \text{ AND } d.object \text{ contains } x)\rbrace, 
\end{aligned}
$$

and the **bipartite document frequency** for such a pair is

$$
f(x, y) = \vert \vert S(x, y) \vert \vert.
$$

The calculation of NGD based on document frequencies can be found in [BioThings_Explorer_TRAPI - Issue#326](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/326) 

### 2.2 Setwise Document Frequencies

We can further expand a term into a set/collection of terms in our above definition. 

If we have a set of single terms 

$$
\mathbf{X} = \lbrace x_1, x_2, \dots, x_m \rbrace,
$$ 

its **setwise unary document frequency** can be defined as

$$
f(\mathbf{X}) = \vert \vert S(\mathbf{X}) \vert \vert,
$$

where

$$
S(\mathbf{X}) = S(x_1) \cup S(x_2) \cup \dots \cup S(x_m).
$$

Note: suppose there is a document `d` containing all terms, it should contribute only `1` (not `m`) to the setwise document frequency. That's why  

$$
f(\mathbf{X}) \neq f(x_1) + \dots + f(x_m).
$$

Similarly, when we have a set of paired terms 

$$
\mathbf{P} = \lbrace (x_1, y_1), (x_2, y_2), \dots, (x_m, y_m) \rbrace,
$$

we define its **setwise bipartite document frequency** as

$$
f(\mathbf{P}) = \vert \vert S(\mathbf{P}) \vert \vert,
$$

where

$$
S(\mathbf{P}) = S(x_1, y_1) \cup S(x_2, y_2) \cup \dots \cup S(x_m, y_m).
$$

Specially when there is only term or pair in the sets:

$$
\begin{aligned}
\mathbf{X'} &= \lbrace x_1 \rbrace \newline
\mathbf{P'} &= \lbrace (x_1, y_1) \rbrace,
\end{aligned}
$$

we have:

$$
\begin{aligned}
f(\mathbf{X'}) &= f(x_1) \newline
f(\mathbf{P'}) &= f(x_1, y_1).
\end{aligned}
$$

Therefore we can conclude that **vanilla document frequencies are just a special case of setwise document frequencies**.

### 2.3 Term Expansion

In our application, we **expand** a single term `x` by inclusion of all its children (or [narrower entities in UMLS terminology](https://www.nlm.nih.gov/research/umls/new_users/online_learning/SEM_006.html)), making a set of terms including `x`: 

$$
x \Rightarrow \lbrace x \rbrace \cup \lbrace x_i \mid x_i \text{ is a child of } x \rbrace.
$$

<details>
<summary>Click to unfold the original description using "star graphs".</summary>

This would make a perfect example of [star graphs](https://en.wikipedia.org/wiki/Star_(graph_theory)) where the center/root term is `x`:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Star_network_7.svg/360px-Star_network_7.svg.png)

That's why I chose the word "star" over others like "cluster" or "group" in my Python code.
</details>

## 3. HTTP Parameter Design

A new optional parameter `expand` can be passed in, e.g. in a GET query:

```python
http://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063&expand=both
```

- If not passed in, or `expand=nil`, no terms will be expanded
- If `expand=left`, only the left-hand-side term in the pair (i.e. `C0684074` in the above example) will be expanded
- If `expand=right`, only the right-hand-side term in the pair (i.e. `C0003063` in the above example) will be expanded
- If `expand=both`, both terms will be expanded.

Note that the acceptable values are case-insensitive, e.g. `NIL`, `Left`, `RiGhT` and `bOtH` are all legal. Non-acceptable values will lead to a `400` error.

POST queries work similarly, e.g.:

```bash
curl -X POST http://biothings.ncats.io/semmeddb/query/ngd \
-H 'Content-Type: application/json' \
-d '{"umls": [["C0684074", "C0003063"], ["C0007450", "C0007350"]], "expand":"both"}'
```

<details>
<summary>Click to unfold Design Proposal No.2.</summary>

### 3.2 Design No.2 (proposal)

Simply append an asterisk (`*`) to the term or terms we want to expand. E.g. 

```python
# Expand both terms
http://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074*,C0003063*
```

```bash
# Expand the left-hand-side term in the 1st pair
# Expand the right-hand-side term in the 2nd pair
curl -X POST http://biothings.ncats.io/semmeddb/query/ngd \
-H 'Content-Type: application/json' \
-d '{"umls": [["C0684074*", "C0003063"], ["C0007450", "C0007350*"]]}'
```

**Pros:** Easy to implement, kind of cool (in my eyes)
**Cons:** Might be hard to read, risk of overlooking

</details>

<details>
<summary>Click to unfold Design Proposal No.3.</summary>

### 3.3 Design No.3 (proposal)

Add a new parameter to indicate which terms to expand. E.g.

```python
# Expand only one
http://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063&stars=C0684074
http://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063&stars=C0003063

# Expand both
http://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063&stars=C0684074,C0003063
```

```bash
# Expand the left-hand-side term in the 1st pair
# Expand the right-hand-side term in the 2nd pair
curl -X POST http://biothings.ncats.io/semmeddb/query/ngd \
-H 'Content-Type: application/json' \
-d '{"umls": [["C0684074", "C0003063"], ["C0007450", "C0007350"]], "stars": [["C0684074"], ["C0007350"]]}'
```

**Pros:** Fine-grained control
**Cons:** more argument verification work, might be too verbose for a long POST queries

</details>

## 4. Response Design

E.g. with the following GET query:

```python
https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063&expand=both
```

we will have a response like this:

```python
{
  "ngd": 0.9819639606807624,
  "umls": [
    "C0684074",
    "C0003063"
  ],
  "expand": "both",
  "leaf_umls": {
    "C0684074": null,
    "C0003063": ["C0032850", "..."]
  }
}
```

Note that:

1. `"ngd"` field is the NGD value (float type, or a string of `"Infinity"` or `Undefined` when errors occur)
2. `"umls"` and `"expand"` fields are copied from arguments
    - Even if `expand` argument is not passed in the URL, we will still see a `"expand": "nil"` field in the reponse
4. `"leaf_umls"` contains `<parent-term>: <child-terms>` relationships:
    - If a parent term is not expanded, it won't appear as a key in field `leaf_umls`.
    - If none of the two parent terms is expanded, the whole `"leaf_umls"` field won't appear in the response.
    - A `null` value in `leaf_umls` means that parent term is expanded but no children is found.

POST queries' response will be similar.

## 5. Example Queries and Responses

Consider `C0683949` ("Animal Study") and `C0599779` ("Animal Model"). 

- `http://biothings.ncats.io/semmeddb/query/ngd?umls=C0599779,C0683949&expand=nil`
  <details>
  <summary>Click to view response</summary>
  
  ```python
  {
    "ngd": 0.8638765828501777,
    "umls": [
      "C0599779",
      "C0683949"
    ],
    "expand": "nil"
  }
  ```
  </details>
- `http://biothings.ncats.io/semmeddb/query/ngd?umls=C0599779,C0683949&expand=left`
  <details>
  <summary>Click to view response</summary>

  ```python
  {
    "ngd": 0.8768665471254184,
    "umls": [
      "C0599779",
      "C0683949"
    ],
    "expand": "left",
    "leaf_umls": {
      "C0599779": [
        "C1518385",
        "C1154340",
        "C5205861",
        "C1512041",
        "C0012644",
        "C1519606",
        "C4042865",
        "C1519674",
        "C4053909"
      ]
    }
  }
  ```
  </details>
- `http://biothings.ncats.io/semmeddb/query/ngd?umls=C0599779,C0683949&expand=right`
  <details>
  <summary>Click to view response</summary>

  ```python
  {
    "ngd": 1.184998800769695,
    "umls": [
      "C0599779",
      "C0683949"
    ],
    "expand": "right",
    "leaf_umls": {
      "C0683949": [
        "C0599779",
        "C0681856"
      ]
    }
  }
  ```
  </details>
- `http://biothings.ncats.io/semmeddb/query/ngd?umls=C0599779,C0683949&expand=both`
  <details>
  <summary>Click to view response</summary>

  ```python
  {
    "ngd": 1.1886867122565343,
    "umls": [
      "C0599779",
      "C0683949"
    ],
    "expand": "both",
    "leaf_umls": {
      "C0599779": [
        "C1518385",
        "C1154340",
        "C5205861",
        "C1512041",
        "C0012644",
        "C1519606",
        "C4042865",
        "C1519674",
        "C4053909"
      ],
      "C0683949": [
        "C0599779",
        "C0681856"
      ]
    }
  }
  ```
  </details>

Error messages for invalid requests are identical as described in [BioThings_Explorer_TRAPI - Issue#326](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/326)

**Comment by erikyao** [comment]
Code 99% done on my fork, https://github.com/erikyao/pending.api.

Last problem to solve: to find a proper location for the UMLS narrow-relationship JSON file (from Eric Zhou) on the biothings.ncats.io server. Current specification on https://github.com/erikyao/pending.api/blob/master/config_web/semmeddb.py#L5 only works for `su06`.

**Comment by erikyao** [comment]
## 6. Code Structure (TBD)

![mermaid-diagram-2022-08-23-154847](https://user-images.githubusercontent.com/4813680/186279558-db17d8a1-a53d-4636-a831-de3402d37581.png)

**Comment by andrewsu** [comment]
per 2022-08-24 meeting, @erikyao will adjust the `leaf_umls` output structure

**Comment by erikyao** [comment]
> per 2022-08-24 meeting, @erikyao will adjust the `leaf_umls` output structure

Updated with [pending.api - PR#81](https://github.com/biothings/pending.api/pull/81)
