### ISSUE TITLE
phenotype API can be removed now

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#84]
https://github.com/biothings/pending.api/blob/master/config_web/phenotype.py

I believe it's replaced by https://biothings.ncats.io/hpo

**Comment by newgene** [comment]
potentially use the deprecation mechanism in #86

**Comment by erikyao** [comment]
## Job 1

Do not expose `phenotype.py` to `__init__.py` in the `config_web`.

Finished with commit 877cf978d5b753c18357d8e0c112da7bcb482c40

## Job 2

We have the following two aliases in ITRB prod:

1. `pending-phenotype` assigned to index `hpo_20220903_caysx6dd`
2. `pending-hpo` assigned to index `hpo_20220903_caysx6dd`

Delete the first one to reduce the risk of overwriting.
