### ISSUE TITLE
Create a global /api/list endpoint to return available APIs

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#87]
See this code comment:

https://github.com/biothings/pending.api/blob/ee9508d0c81f03515675b77f46a4b0149d76e871/web/handlers/__init__.py#L45-L53

This /api/list was available from the hub. We no do not run a deployment hub on prod server, so we implemented a temp solution. But this /api/list endpoint should be useful in general.

**Comment by erikyao** [comment]
Boils down to implement endpoint `https://biothings.ncats.io/api/list`

See above ref implementation.

**Comment by erikyao** [comment]
Also consider "deprecated" status, see https://github.com/biothings/pending.api/issues/86
