### ISSUE TITLE
UI issue for queries with colons and quotation marks? 

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#97]
When I go to https://pending.biothings.io/biggim_drugresponse_kp, select "Write My Own Query", and put `/query?q=association.edge_label:"biolink:positively_correlated_with" AND subject.NCBIGene:"NCBIGene:988"` into the box, I get no hits. 

When I look at the url generated, I notice that it has more escape characters than I would expect: `https://pending.biothings.io/biggim_drugresponse_kp/query?q=association.edge_label:"biolink\:positively_correlated_with" AND subject.NCBIGene\:"NCBIGene\:988`

When I paste a url without the escape characters into a browser, I get hits (total says 96): `https://pending.biothings.io/biggim_drugresponse_kp/query?q=association.edge_label:%22biolink:positively_correlated_with%22%20AND%20subject.NCBIGene:%22NCBIGene:988%22`

**Comment by erikyao** [comment]
Hi @marcodarko, could you please take a look at this issue? Please let me know if it can be fixed at the front end. Thanks!

**Comment by marcodarko** [comment]
@erikyao should be resolve in latest commit, feel free to push to prod when ready. 👍
